### ISSUE TITLE
The Card Draw Simulator UI bug is back...

### ISSUE THREAD

**Issue by Esutter479** [Null-Signal-Games/netrunnerdb#1]
I hate to be the bearer of bad news, but I'm getting that pesky "gap in UI" bug that was happening before.  It's true, it WAS fixed the other day, and I enjoyed a nice bug-less few hours theorizing some decks for myself.  It is, however, back and doing the exact same stuff as last time.  Cards from All That Remains up until current packs are causing the mishap, unless they're in the first row, last row or the last card appearing in any row.  It'd be great if this could be re-explored and the problem solved so it doesn't crop up again.

**Comment by alsciende** [comment]
Bug disappearing and reappearing, that's a first.

**Comment by alsciende** [comment]
Seems like it's a cache issue. Can you do a force-refresh?

**Comment by Esutter479** [comment]
Yep, that seems to be it...cache.  I forced a refresh, and now the cards are loading up normally with the simulator.  Thank you for the advice, Alsciende. :)  I'll keep my fingers crossed that it doesn't happen anymore.
