### ISSUE TITLE
Support for the New MWL 1.2

### ISSUE THREAD

**Issue by lostie** [Null-Signal-Games/netrunnerdb#100]
As per the [official announcement](https://www.fantasyflightgames.com/en/news/2017/4/12/enhanced-enforcement-tactics/) the new MWL version works in a substantial different way from the previous versions:

> Universal Influence
>
> The first change comes in the form of how the Most Wanted List affects influence. In the new > system, the Most Wanted List’s influence relationship is placed on each individual card. Instead of subtracting 1 influence from the Identity’s influence limit, pips of ‘universal influence’ are now added to cards. Much like its previous iteration, universal influence applies even to in-faction cards.

This change most likely requires some new schema changes to [netrunner-cards-json mwl](https://github.com/zaroth/netrunner-cards-json/blob/f76493282a65afa517a767117e83a1afa8c18271/mwl.json) and a new functionality to support Universal Influence.

> Levels
>
> The second change comes in the form of different levels of universal influence. Some cards are too powerful to be modified by a shift of only 1 influence, creating the need for flexibility in addressing them.
>
> Levels add an amount of universal influence to a card equal to that level. For instance, if a card is on level 1, it gains 1 universal influence. If it’s on level 3, it gains 3 universal influence. Levels greatly aid in accurately curtailing each and every card’s potency.

For this one it seems this might already be supported as the current schema for the cards in the MWL has an associated number (which until now was always 1).

/cc @Alsciende

**Comment by alsciende** [comment]
Thank you for the summary and analysis.

**Comment by alsciende** [comment]
I'm afraid FFG is going to print cards with universal influence, some time soon.

**Comment by beardsley-james** [comment]
is universal influence functionally identical to neutral influence?

**Comment by alsciende** [comment]
AFAIK, yes.

**Comment by lostie** [comment]
Well, kind of. 

My interpretation of the reason that Boggs decided to call it something else is, presumably, to avoid situations where cards like [Mumba Temple](https://netrunnerdb.com/en/card/10018), while on the MWL, would still be influence 0 if you have 15 or fewer ice in your deck.

So even when the Alliance cards meet their criteria to be influence 0, the universal influence would still apply.

**Comment by alsciende** [comment]
Good point.

I updated the server with an implementation of MWL 1.2. I'm sure there are a few bugs lying around, but I wanted to add it quickly, since the MWL is taking effect "immediately"...
