### ISSUE TITLE
[MWL 1.2] Universal influence

### ISSUE THREAD

**Issue by Keizhac** [Null-Signal-Games/netrunnerdb#103]
Sorry for english people but, I'm very bad in english so ...  Sorry ^^

When you choose a same faction card in MWL (like Clone Chip in a Shaper deck) the universal influence is not counted.
In fact I think it's not counted at all.
(Ndlr : la prochaine fois je me foule pas et je fais le report en français, je suis trop mauvais en anglais :p)

**Comment by alsciende** [comment]
C'est très bizarre ce que tu me dis là ! Je ne reproduis pas le problème.

![image](https://cloud.githubusercontent.com/assets/391974/25140398/6fe98e14-2460-11e7-995d-3d5d43074aeb.png)
![image](https://cloud.githubusercontent.com/assets/391974/25140429/8cba2922-2460-11e7-8bf7-0a1487677f4c.png)

**Comment by Keizhac** [comment]
Bah oui, surtout qu'un collègue a testé chez lui et ne reproduit pas non plus
![image](https://cloud.githubusercontent.com/assets/7223220/25141463/e7334dea-2463-11e7-9a87-fdd9875bb76f.png)
Mais comme dans le screen ci-dessus, je reproduis (je t'ai pas tout screen mais j'ai bien mis MWL 1.2).

Ceci étant dit, je vais tester chez moi ce soir de toute façon (j'ai des decks  faire pour demain), je verrais si ça me le refais ou pas. Ca se trouve y'a un truc qui bloque au boulot (même si ma console ne me dit rien de particulier mais bon ...)

Je te tiens au courant

**Comment by Keizhac** [comment]
Bon, et bien chez moi je ne reproduis pas. Cas isolé donc, à creuser si je le reproduis vraiment ailleurs qu'au boulot ^^
