### ISSUE TITLE
Cards on MWL are always showing in deckbuilder, even if their pack is excluded

### ISSUE THREAD

**Issue by AdrianHerber** [Null-Signal-Games/netrunnerdb#108]
Repro steps:
Start building a deck
Go to collection tab and untick some datapacks, eg everything except core set and TD
Go to build tab and toggle on all factions and card types
MWL cards eg Faust are appearing, when they shouldn't be.

**Comment by alsciende** [comment]
I can't reproduce. Are you sure your World Champion decks are unselected?

**Comment by AdrianHerber** [comment]
Ah, oops :( Yep, I had failed to untick them. Sorry!
