### ISSUE TITLE
Feature request: Cache refresh legality checker

### ISSUE THREAD

**Issue by JacktheScott** [Null-Signal-Games/netrunnerdb#111]
Similar to NAPD check... Biggest issue is the ability to limit a single core  set.

**Comment by yads** [comment]
To summarize the deck building rules:
* MWL in effect
* 1 Core Set
* 1 Terminal Directive
* 1 Deluxe Expansion
* Current cycle
* Previous cycle

**Comment by alsciende** [comment]
Fixed by https://github.com/Alsciende/netrunnerdb/pull/131
