### ISSUE TITLE
Decklist->history->revert not working

### ISSUE THREAD

**Issue by jmm13** [Null-Signal-Games/netrunnerdb#115]
It doesn't appear that the Revert link for deck editing is working. Click it, nothing happens. Tried both on chrome/desktop and ios/safari, same result

**Comment by jmm13** [comment]
It's just the first Revert link listed that doesn't do anything. I misunderstood how it worked, but to be fair, it's not really clear. is a link even necessary for the first history item?

**Comment by plural** [comment]
I'm closing this off.

It is a bit clunky to hide the Revert link if you only have a single version of the deck.  Reverting for other versions does the right thing and clicking revert on the first version when you have more versions works as well.
