### ISSUE TITLE
On-hover card preview doesn't display art

### ISSUE THREAD

**Issue by eljenso** [Null-Signal-Games/netrunnerdb#119]
Using Chrome Version 59.0.3071.115 (Official Build) (64-bit), also checked in private mode (all addons disabled).
Screenshot of bug in action:
![selection_023](https://user-images.githubusercontent.com/2805194/27862210-760044da-6184-11e7-9d8e-66723525bcea.png)

Sometimes the art does show (for example, in the first preview generated on every page but also at random).

**Comment by alsciende** [comment]
You can execute "NRDB.tip.set_hide_event('unfocus');" in the console to prevent the tooltip from auto-hiding on mouseover. That might help you find what's causing the issue.


Le 5 juillet 2017 à 14:25, Jens Böttcher <notifications@github.com> a écrit :

Using Chrome Version 59.0.3071.115 (Official Build) (64-bit), also checked in private mode (all addons disabled).
Screenshot of bug in action:

Sometimes the art does show (for example, in the first preview generated on every page but also at random).

**Comment by eljenso** [comment]
Are the DOM nodes of the qtips supposed to be deleted when moving to another link?
Because when I move my mouse over multiple links, some nodes get deleted and some don't.

Also, when I delete all qtip nodes and then move my mouse over a link, the new qtip is shown correctly.

Another strange observation: when I make the first qtip visible again (by changing it's style), the art for all the other qtips appear as well.

**Comment by eljenso** [comment]
Created a gif with the bug in action: https://i.imgur.com/hrW1HNa.gifv
