### ISSUE TITLE
Add required packs to decklist page

### ISSUE THREAD

**Issue by jonmorris** [Null-Signal-Games/netrunnerdb#12]
It would be great to add a list similar to the card list that includes all of the packs you'd need to own in order to build the current deck. Maybe including the number of packs in the case of the core set. Another similar feature could be letting users submit what packs they own and be able to filter by decks they could build.

Something roughly like this:
![screenshot 2016-06-23 12 14 43](https://cloud.githubusercontent.com/assets/3299032/16310948/87781f88-393c-11e6-9b50-cda1ab852b7f.png)

**Comment by jonmorris** [comment]
Maybe you don't need to break it out by big box vs data packs. Maybe you just list them in 2 columns in either alpha or chrono (release) order.

**Comment by CoryOwens** [comment]
As a workaround, you can sort by Set on the decklist page, and it makes it pretty easy to see which packs you need, although it won't tell you if you need multiple core sets.

**Comment by alsciende** [comment]
I didn't count the number of packs needed. Too lazy. But PR are welcome =)

**Comment by jonmorris** [comment]
Killer - thank you
