### ISSUE TITLE
Feature Request: API to get translated card information

### ISSUE THREAD

**Issue by nitamago** [Null-Signal-Games/netrunnerdb#122]
# API to get the translated card text.
I know netrunnerdb API that get the card information.
I want to get the traslated card text with API. 
But current API fetches the English card information.

_Sent from my Sony SGP321 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alsciende** [comment]
Try with ?_locale=de

**Comment by nitamago** [comment]
I tried it.
I fetched localized card data.
Thank you.
