### ISSUE TITLE
Not getting e-mail for password

### ISSUE THREAD

**Issue by thedolph** [Null-Signal-Games/netrunnerdb#125]
For some reason when I tell the system to reset my password I never receive an Email.

**Comment by Deebster** [comment]
I just received one, but it was in spam due to SPF failures.

SPF record says ```v=spf1 +mx -all``` but since there are no mx records, no outgoing email is considered valid.

**Comment by jackeys** [comment]
I'm also unable to get this email. It's not showing up in my junk email, either.

Which address does the password reset email come from now?

**Comment by gereons** [comment]
Same issue here, regardless of where I try to have this email sent to, it never arrives.

**Comment by alsciende** [comment]
It should be fixed now. Mails won't be sent to Microsoft accounts until I've been unblocked, in a few days.

**Comment by gereons** [comment]
Thank you, worked for me now.
