### ISSUE TITLE
Cannot publish deck affected by deck limit errata

### ISSUE THREAD

**Issue by DrTall** [Null-Signal-Games/netrunnerdb#128]
Hello,

I'd like to publish an old deck of mine which was legal when I made it back in 2014. The deck isn't legal today because of the errata to AstroScript Pilot program, but I don't think I should be prevented from publishing the deck.

It might not seem like a big deal, but I am trying to get some new players into the game and sharing old decks of mine which only contain cards they own would be helpful.

Thanks,
Sean

**Comment by alsciende** [comment]
Hello Sean,

I'm sorry but I cannot allow exceptions to the deck legality rule or the card errata as long as NetrunnerDB doesn't have a system of "deck format".

A solution for you is to simply share the link of your private deck with those new players. If you didn't disable it in your account preferences, they'll be able to see your deck.

**Comment by DrTall** [comment]
Thanks for the response, and I do understand it is difficult to please everyone. I guess my two cents is that it is strange that violations of the MWL are treated so differently from violations of the deck limit, when they both seem equally harmless or harmful depending on one's perspective.

**Comment by alsciende** [comment]
The rationale is that the rulebook imposes the deck limit to all players, while the MWL is only enforced during (serious) tournaments :)

**Comment by DrTall** [comment]
As a counterexample, the Core Set rulebook still suggests an NBN starter deck which can't be published on netrunnerdb. :) But I'll drop it. Thanks for your consideration!
