### ISSUE TITLE
Improving Card Names

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#129]
It would be nice if it would be possible to find cards like Sifr through the search. You need to use keys on the keyboard which are hard to find for me and even to remember. So it would be nice if there could be a second field in the database which could have an alternative name to make finding strange card names easier with a standard keyboard.
When typing "Sifr" into the search he won't find this card.

**Comment by plural** [comment]
Hmm, i'm not able to reproduce this.  I can take a look for some more cards with special characters to see if this is reproducible.

https://netrunnerdb.com/find/?q=Sifr brings Şifr 
https://netrunnerdb.com/find/?q=%C5%9Eifr

https://netrunnerdb.com/find/?q=S%C5%ABnya
https://netrunnerdb.com/find/?q=Sunya

**Comment by ghost** [comment]
is it possible that this was not working in the past and is working now? I noticed this too.

**Comment by plural** [comment]
Ah, @Alsciende clarified for me.  This works in the main search, which is server-side.  The search used in the deck editor is client side, though, and that doesn't find the card without an exact match.
