### ISSUE TITLE
[Bug] Card Filtering Not Respecting Collection Choices

### ISSUE THREAD

**Issue by j-paro** [Null-Signal-Games/netrunnerdb#130]
I was building a Cache Refresh deck and I had only C&C selected along with the last two cycles and Terminal Directive. When selecting cards I can still see the cards from unselected data packs.

![image](https://user-images.githubusercontent.com/30871900/29131189-b61c6c3c-7cf1-11e7-94d2-10d2e026be47.png)

![image](https://user-images.githubusercontent.com/30871900/29131213-cf3acac4-7cf1-11e7-9b64-ee73b0818421.png)

**Comment by doorisajar** [comment]
I have a similar issue even after refreshing / cache clear etc -- the cards don't appear in the list, but they're still found by the search box. So e.g. when I deselect for rotation (including deselecting the Worlds decks), but search for Jackson in the deckbuilder search box, he still comes up.

**Comment by alsciende** [comment]
@BizTheDad what cards should not be displayed in your example? Are you sure these are not cards from the World Championship Decks?

**Comment by j-paro** [comment]
I had the World Champs' decks selected. That's why I was getting cards like Scrubber and what not to show up. Turns out this "bug" was my fault. Thanks for taking a look at it.
