### ISSUE TITLE
Feature Request card links to original netrunner cards

### ISSUE THREAD

**Issue by ANR-PeterPan** [Null-Signal-Games/netrunnerdb#132]
Now that this site exists : http://www.emergencyshutdown.net/webminster
could u make a link at the cards page to its correspondant original card?
like this http://www.emergencyshutdown.net/webminster/cards/303 for this https://netrunnerdb.com/en/card/01099 ?

**Comment by NoahTheDuke** [comment]
I don't think we're going to do that. Thanks for the idea tho.
