### ISSUE TITLE
Deck builder showing no cards or packs, even after clearing browser cache

### ISSUE THREAD

**Issue by haradan** [Null-Signal-Games/netrunnerdb#133]
The deck builder is missing all cards, even after I clear all my browser data from the beginning of time in Chrome 60.0.3112.101. Strangely, if I use an incognito window I don't get this issue.

![image](https://user-images.githubusercontent.com/6625241/29682089-ac069dd2-8901-11e7-87a1-94fd81d5bcfe.png)

![image](https://user-images.githubusercontent.com/6625241/29682107-b5c9968a-8901-11e7-8262-6140f9677807.png)

**Comment by alsciende** [comment]
Check your browser settings. You may have a settings that prevents netrunnerdb.com from accessing localStorage.

**Comment by haradan** [comment]
NetrunnerDB definitely has permission to access localStorage. It is storing some things in there, it's just not getting cards or packs.

**Comment by ANR-PeterPan** [comment]
i have a similar prob. sometimes my decks are empty, a little later all works fine.
using mozilla on pc and android
![grafik](https://user-images.githubusercontent.com/24223024/29730367-319309ca-89e0-11e7-8174-11784e16fb96.png)
![grafik](https://user-images.githubusercontent.com/24223024/29730400-50cc61ce-89e0-11e7-946c-9bb6a2eaa3ec.png)

**Comment by ANR-PeterPan** [comment]
lol, just as i said, now everything is fine again:
![grafik](https://user-images.githubusercontent.com/24223024/29730448-7b063c62-89e0-11e7-8cbd-0116a88115c7.png)

**Comment by haradan** [comment]
Mine never seems to load the cards at all, and it won't let me open any of my decks. Nothing happens when I click them in the list under "My Decks".

**Comment by haradan** [comment]
This stopped happening for a long time but now it's back again. Still no indication of what's wrong or how to fix it. I've tried using Chrome's developer tools to clear all browser storage for the site and it still happens. I also can't view any decks, it doesn't load the list of cards.

**Comment by gereons** [comment]
This is definitely an issue with local storage, as the JavaScript console logs I got indicate.

I struggled with this in Firefox 57 just now (in Chrome everything worked fine), and it turned out I had to delete the "storage.sqlite" database from my Firefox profile to get this working again.

**Comment by haradan** [comment]
It's working for me again, but I didn't change any settings.
