### ISSUE TITLE
NetrunnerDB Card Tooltip demo is not works.

### ISSUE THREAD

**Issue by eai04191** [Null-Signal-Games/netrunnerdb#135]
https://netrunnerdb.com/tools/demo

Error on Chrome 60.0.3112.113

```
nrdb.data.js:217 Uncaught ReferenceError: NRDB is not defined
    at nrdb.data.js:217
(anonymous) @ nrdb.data.js:217
nrdb.format.js:56 Uncaught ReferenceError: NRDB is not defined
    at nrdb.format.js:56
(anonymous) @ nrdb.format.js:56
nrdb.tip.js:91 Uncaught ReferenceError: NRDB is not defined
    at nrdb.tip.js:91
```

**Comment by plural** [comment]
@Alsciende is this functionality desired, still?  I see https://github.com/Alsciende/netrunnerdb/commit/6a87674415b4ed1c1280161f564a1b2d8a0528d5#diff-e5913333bd2844bcd01efb3dbdecfc02 looks like the cause for this no longer working.

What are your thoughts here?

**Comment by NoahTheDuke** [comment]
Seems to be working now.

**Comment by plural** [comment]
i'm still seeing these errors at least on the https://netrunnerdb.com/tools/demo page.

are there new versions of the js files that aren't at the URLs on the demo page or is there still an issue?

I'm on chrome 71 right now, fwiw.

**Comment by x3N1GM4x** [comment]
I also see these errors on the demo page as described by @plural:
![image](https://user-images.githubusercontent.com/10621139/51317444-7ccc1980-1a4f-11e9-8a82-55e2e41aa7b6.png)
