### ISSUE TITLE
Feature Request: Championship Deck packs selectable in Deck Search

### ISSUE THREAD

**Issue by moyarzun** [Null-Signal-Games/netrunnerdb#137]
Having the Championship Decks available as selectable data packs on Deck Search may help us newcomers who bought them to find premade decks alongside whatever other Data Packs we own. This is already a feature on the Deck Builder, can it be done on the Deck Search, too?

**Comment by alsciende** [comment]
Although that is a nice idea, it's currently not possible because of the way Championship Decks are implemented.
