### ISSUE TITLE
Legality and Errata on Card Page

### ISSUE THREAD

**Issue by NoahTheDuke** [Null-Signal-Games/netrunnerdb#14]
I think including the legality of a given card on it's card page would be helpful. It's a little soon, but some time next year data packs will rotate out and thus some cards will become unavailable for tournament play. Within that, marking if a card is on the Most Wanted List or is Unique could be very helpful.

For example: ![Prepaid VoicePAD](http://i.imgur.com/ZEgs3FY.png)

Additionally, noting exactly what changed from a FAQ or errata instead of just noting that it did change would be helpful.

For example: ![e3 Feedback Implants](http://i.imgur.com/m09fZmW.png)

Obviously, these look like crap, but I think a touched up version would be really helpful. I wish I knew php so I could do it myself.

Thanks so much!

**Comment by alsciende** [comment]
I agree on the first point. I'm not going to address the second point. The link to ANCUR should provide all the relevant information concerning the FAQs.
