### ISSUE TITLE
Cache Refresh + Revised Core Set validation is inconsistent

### ISSUE THREAD

**Issue by admanb** [Null-Signal-Games/netrunnerdb#144]
This one's pretty weird. My SYNC and Chaos Theory decks, which are both CR compliant with the revised core, are failing compliance. I dug into it a bit and found that specifically what breaks the SYNC deck is SYNC+Project Beale. But if I make an NBN deck with Making News as the identity and add Project Beale, it works!

**Comment by yads** [comment]
I don't think the CR check has been updated to handle revised core.
