### ISSUE TITLE
Unable to access Decklists

### ISSUE THREAD

**Issue by peppermintreina** [Null-Signal-Games/netrunnerdb#146]
I'm unable to access my own decklists at the moment.  I log in, but when I click on My Decklists I'm prompted to log in again.  When I enter my details, I'm looped back to the homepage again.  This continues on a loop every time I click on My decklists again.
Don't know if it is linked or not but I tried to create a new account with a second email address and received an about an invalid CSRF token.  Can't get around this either.

**Comment by alsciende** [comment]
It should again now.
