### ISSUE TITLE
Collection is blank

### ISSUE THREAD

**Issue by posttrib777** [Null-Signal-Games/netrunnerdb#147]
I'm attempting to filter out the data packs that are rotating out but the card collection is blank for me. I had done this already but found that rotated cards are showing in my options leading me to attempt to enter Collections again to find no packs to choose.

I also have to select obsolete Most wanted list then to show any of my decks that exist in my library.
I'm running Safari 10.1.2

**Comment by avandever** [comment]
Can you try a cache reset while on that page?
cmd + shift + r, see more [here](https://superuser.com/questions/186594/how-can-i-force-safari-to-perform-a-full-page-reload-without-using-the-mouse).

**Comment by posttrib777** [comment]
Everything seems to be working now.

Thank you.

Ben
