### ISSUE TITLE
Card Reviews

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#150]
When a card review is done, this is usually based on a specific card pool. With Rotation coming and the new core I think it would be useful to track the card pool a review was valid for. The easiest would be if the one writing the review would select it, or if it's done automatically based on the date.

**Comment by alsciende** [comment]
Something like "Written before First Rotation"?

**Comment by ghost** [comment]
I was more thinking about the issue that the review is aligned to a status of the card game. So it would be interesting to know which cards where available at that point in time. Assuming ANR is successful we will have more rotations to come. And on top it might be interesting for someone reading it, what was the available data pack 2 years ago. So I thought it would be an improvement if we could track that along with the review.

**Comment by jdcowf** [comment]
If we could add a "Most recent release at time of publication" to the review that would be a great way to date them, similar to how the "Packs up to" is used in deck viewer.

**Comment by ghost** [comment]
Yes, this sounds like a good solution

**Comment by ghost** [comment]
thanks for implementing it! Really like it.

**Comment by ghost** [comment]
One thing I realized when updating the review, shouldn't it also update the latest pack at time of writing?

**Comment by x3N1GM4x** [comment]
Tricky - what if someone comes back to one of their reviews a few months later and just corrects a typo or rephrases something? Would you want the "latest pack" to update, artificially making the review seem newer than it really is?

**Comment by ghost** [comment]
Agree. Perhaps it's best to write a total new review.
