### ISSUE TITLE
A few cards illustrated by Tim Durning credited to "Tim Dunning"

### ISSUE THREAD

**Issue by MrCowbird** [Null-Signal-Games/netrunnerdb#154]
Tim Durning has illustrated quite a few cards for Netrunner, including the wonderfully illustrated but recently banned Rumor Mill.

In figuring out illustrators for cards, three of his cards (Bloo Moose, Flashbang, Traffic Analyzer) were credited to Tim Dunning:

https://netrunnerdb.com/find/?q=i%3A"Tim+Dunning"

Turns out Rumor Mill isn't the only banned card he illustrated!

**Comment by yads** [comment]
@MrCowbird the card data is available in https://github.com/Alsciende/netrunner-cards-json/

The card data (including the illustrator) is under https://github.com/Alsciende/netrunner-cards-json/tree/master/pack

**Comment by MrCowbird** [comment]
Great! I think I can fix this.

Thanks, I see now where I overlooked things directing me towards that github rather than this one. Appreciate the direction.
