### ISSUE TITLE
Card previews do not contain image thumbnails in Firefox 56.0.1

### ISSUE THREAD

**Issue by SpencerDub** [Null-Signal-Games/netrunnerdb#161]
Hovering over a card link in Firefox 56.0.1 causes the card preview to appear. However, the preview does not contain the art thumbnail in the upper-right corner--neither the image itself nor its hexagonal frame.

---

![netrunnerdb - firefox card preview](https://user-images.githubusercontent.com/4674927/31803932-480ee1c8-b50b-11e7-9135-3450455551e1.JPG)
-*Card preview in Firefox 56.0.1*

---

When viewing in other browsers (Edge 38.14393.1066.0, Chrome 61.0.3163.100), the thumbnail and the hexagon appear as expected:

---

![netrunnerdb - edge card preview](https://user-images.githubusercontent.com/4674927/31803895-1a490048-b50b-11e7-98be-c70f0df299e3.JPG)
-*Card preview in Edge 38.14393.1066.0*

---

![netrunnerdb - chrome card preview](https://user-images.githubusercontent.com/4674927/31803938-4e13e5a0-b50b-11e7-8c89-5e175d7a3f5f.JPG)
-*Card preview in Chrome 61.0.3163.100*

---

I have tested this in Firefox 56.0.1 Safe Mode, with all add-ons disabled. The behavior is the same.

Is this a bug? Or is Firefox just not capable of displaying the thumbnails for some reason?

**Comment by alsciende** [comment]
Firefox doesn't support correctly the tools I use to display the thumbnails. So it's not a bug, it's a feature ;)

**Comment by SpencerDub** [comment]
Cool, just thought I'd check! Thanks for the info.

**Comment by eljenso** [comment]
> Firefox doesn't support correctly the tools I use to display the thumbnails.

@Alsciende Could you please elaborate?

I recently switched back to Firefox (57.0.1) and saw that the thumbs are missing. Looked into the code and saw [the cause](https://github.com/Alsciende/netrunnerdb/blob/b9d8bddb63e2e7f49a5bd1c0b7c8eef52e91b425/src/AppBundle/Resources/public/js/nrdb.tip.js#L34) for it.  
What is this check for? I set `image_svg` manually and it worked.
