### ISSUE TITLE
Hovering over card types in the deck building card suggestion list shows "[Object object]"

### ISSUE THREAD

**Issue by liamdawson** [Null-Signal-Games/netrunnerdb#163]
Presumably, something is setting the text to an object instead of a property of the object?

![image](https://user-images.githubusercontent.com/760143/32098824-ae494222-bb59-11e7-9263-88e2f5b563ab.png)

**Comment by x3N1GM4x** [comment]
Believe this was resolved by #166, although due to #217 cannot explicitly test right now.
