### ISSUE TITLE
"My Decks" for Jinteki faction showing NBN logo

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#174]
This started this evening:

![image](https://user-images.githubusercontent.com/10621139/34075106-604e315e-e2b4-11e7-805f-39ada5ca8321.png)

Seems 2/3 of my Jinteki decks are displaying the NBN logo for some reason?

**Comment by x3N1GM4x** [comment]
I think this might be related: When I open the card page for Jinteki: Personal Evolution (https://netrunnerdb.com/en/card/20093), I see the card art for NBN: Making News:

![image](https://user-images.githubusercontent.com/10621139/34080136-2b26a84e-e331-11e7-80d2-3115181040b8.png)

I think #175 which I also logged is probably related, guess some of the new card art got uploaded incorrectly or something.

**Comment by alsciende** [comment]
Fixed, thank you.
