### ISSUE TITLE
Making News card page shows art for Hostile Takeover

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#175]
Might be related to #174, but when I open the card page for NBN: Making News (https://netrunnerdb.com/en/card/20109), I see the new revised art for Hostile Takeover:

![image](https://user-images.githubusercontent.com/10621139/34080108-e0208496-e330-11e7-96fa-3735af372aa9.png)

I accessed the card page via search results, specifically a search for "e:core2|cac|hap|oac|dad t:identity", where I was trying to see all the IDs for the revised core plus deluxe expansions.

**Comment by x3N1GM4x** [comment]
Braintrust (https://netrunnerdb.com/en/card/20094) also shows the art for Project Beale:

![image](https://user-images.githubusercontent.com/10621139/34080243-f24b91a4-e332-11e7-87a4-e0dc315ca542.png)

**Comment by x3N1GM4x** [comment]
Ok, so a full list of card art which appears incorrectly on the site right now:

[Weyland Consortium: Building a Better World](https://netrunnerdb.com/en/card/20077) - shows Jinteki: Personal Evolution
[Hostile Takeover](https://netrunnerdb.com/en/card/20078) - shows Braintrust
[Project Atlas](https://netrunnerdb.com/en/card/20079) - shows Nisei Mk II
[The Cleaners](https://netrunnerdb.com/en/card/20080) - shows Project Junebug
[Dedicated Response Team](https://netrunnerdb.com/en/card/20081) - shows Ronin
[Elizabeth Mills](https://netrunnerdb.com/en/card/20082) - shows Snare!
[GRNDL Refinery](https://netrunnerdb.com/en/card/20083) - shows Himitsu-Bako
[Archer](https://netrunnerdb.com/en/card/20084) - shows Neural Katana
[Caduceus](https://netrunnerdb.com/en/card/20085) - shows Swordsman
[Hadrian's Wall](https://netrunnerdb.com/en/card/20086) - shows Wall of Thorns
[Hive](https://netrunnerdb.com/en/card/20087) - shows Whirlpool
[Ice Wall](https://netrunnerdb.com/en/card/20088) - shows Yagura
[Shadow](https://netrunnerdb.com/en/card/20089) - shows Celebrity Gift
[Beanstalk Royalties](https://netrunnerdb.com/en/card/20090) - shows Neural EMP
[Punitive Counterstrike](https://netrunnerdb.com/en/card/20091) - shows Trick of Light
[Shipment from Kaguya](https://netrunnerdb.com/en/card/20092) - shows Hokusai Grid
[Jinteki: Personal Evolution](https://netrunnerdb.com/en/card/20093) - shows NBN: Making News
[Braintrust](https://netrunnerdb.com/en/card/20094) - shows Project Beale
[Nisei MK II](https://netrunnerdb.com/en/card/20095) - shows TGTBT
[Project Junebug](https://netrunnerdb.com/en/card/20096) - shows Ghost Branch
[Ronin](https://netrunnerdb.com/en/card/20097) - shows Data Raven
[Snare!](https://netrunnerdb.com/en/card/20098) - shows Flare
[Himitsu-Bako](https://netrunnerdb.com/en/card/20099) - shows Pop-Up Window
[Neural Katana](https://netrunnerdb.com/en/card/20100) - shows Tollbooth
[Swordsman](https://netrunnerdb.com/en/card/20101) - shows Wraparound
[Wall of Thorns](https://netrunnerdb.com/en/card/20102) - shows Anonymous Tip
[Whirpool](https://netrunnerdb.com/en/card/20103) - shows Closed Accounts
[Yagura](https://netrunnerdb.com/en/card/20104) - shows Psychographics
[Celebrity Gift](https://netrunnerdb.com/en/card/20105) - shows SEA Source
[Neural EMP](https://netrunnerdb.com/en/card/20106) - shows Red Herrings
[Trick of Light](https://netrunnerdb.com/en/card/20107) - shows Bernice Mai
[Hokusai Grid](https://netrunnerdb.com/en/card/20108) - shows Weyland Consortium: Building a Better World
[NBN: Making News](https://netrunnerdb.com/en/card/20109) - shows Hostile Takeover
[Project Beale](https://netrunnerdb.com/en/card/20110) - shows Project Atlas
[TGTBT](https://netrunnerdb.com/en/card/20111) - shows The Cleaners
[Ghost Branch](https://netrunnerdb.com/en/card/20112) - shows Dedicated Response Team
[Data Raven](https://netrunnerdb.com/en/card/20113) - shows Elizabeth Mills
[Flare](https://netrunnerdb.com/en/card/20114) - shows GRNDL Refinery
[Pop-Up Window](https://netrunnerdb.com/en/card/20115) - shows Archer
[Tollbooth](https://netrunnerdb.com/en/card/20116) - shows Caduceus
[Wraparound](https://netrunnerdb.com/en/card/20117) - shows Hadrian's Wall
[Anonymous Tip](https://netrunnerdb.com/en/card/20118) - shows Hive
[Closed Accounts](https://netrunnerdb.com/en/card/20119) - shows Ice Wall
[Psychographics](https://netrunnerdb.com/en/card/20120) - shows Shadow
[SEA Source](https://netrunnerdb.com/en/card/20121) - shows Beanstalk Royalties
[Red Herrings](https://netrunnerdb.com/en/card/20122) - shows Punitive Counterstrike
[Bernice Mai](https://netrunnerdb.com/en/card/20123) - shows Shipment from Kaguya

**Comment by alsciende** [comment]
Fixed, thank you.

**Comment by x3N1GM4x** [comment]
Errrr, seems this has been resolved by switching the cards, not the images, so decks I had built with any of the above cards have now completely changed?
