### ISSUE TITLE
Contents of decks changed after resolution of #175

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#176]
After the resolution of #175 earlier, it seems many of the cards I had in my decks which were affected have been swapped with the cards they were previously showing the art for, instead of just the art being swapped.

This means people will have to completely rebuild any decks which contained those cards (as IDs have been swapped, they cannot even be edited back to their original state), swapping them back, which is pretty tedious. Any chance the fix could be re-applied in a way which doesn't break decks people have already built?

**Comment by alsciende** [comment]
That's extremely strange. For a brief moment, the card codes were changed, which could have led to some bizarre behaviors like you're describing. But it was reverted and the code are now the same they've always been. Only their position and image_url have been changed, so your decks composition shouldn't be impacted. Can you give the link to one of your affected decks?

**Comment by x3N1GM4x** [comment]
Sure, here's an example: https://netrunnerdb.com/en/deck/view/1052064

I definitely didn't build this deck spending 58 influence... and it was PE when I built it, not Weyland.

**Comment by alsciende** [comment]
I think I might have fixed the issue.

**Comment by x3N1GM4x** [comment]
Looks like there's still a problem to me:

![image](https://user-images.githubusercontent.com/10621139/34101000-3389478e-e3dc-11e7-8f39-2d1e0d5a011d.png)

This deck was originally built with PE as the ID, plus it didn't contain Ghost Branch, Psychographics, SEA Source, Himitsu-Bako, Cadeceus or Flare...

**Comment by yads** [comment]
FWIW, I'm not seeing this behaviour, but I'm also not seeing the new art either, even after loading new card data.

**Comment by alsciende** [comment]
@yads For which card are you seeing the wrong art? Is it in the deckbuilder or the card page?

**Comment by alsciende** [comment]
@x3N1GM4x Is this problem on all your decks that include "Revised Core Set" cards, or just one deck?

**Comment by x3N1GM4x** [comment]
@Alsciende it's any deck which contains Revised Core Set cards as far as I can see.

**Comment by alsciende** [comment]
@x3N1GM4x https://netrunnerdb.com/en/deck/view/1052064 looks good though. Is there a problem with that deck? Can you post a link of a corrupted deck?

**Comment by x3N1GM4x** [comment]
@Alsciende sure, this is the deck I screenshotted above: https://netrunnerdb.com/en/deck/view/1055428

**Comment by alsciende** [comment]
That deck was last updated when the ids were all wrong and stuff were horribly mixed up Sunday. It's quite possible that you edited the deck with the data in your browser, and when you saved it, that data meant something else for the server. I'm very sorry but I don't think I can fix it. If you revert to the previous history point, you should be able to salvage it though.

**Comment by x3N1GM4x** [comment]
No worries, as long as it's fixed going forward, that's the main thing - I was just concerned about other people's decks which might have the same problem, but if there was a narrow window when there was an issue, hopefully it won't affect too many people. Thanks for looking into this though.
