### ISSUE TITLE
Cache Refresh compliance interfering with influence tracking?

### ISSUE THREAD

**Issue by FightingWalloon** [Null-Signal-Games/netrunnerdb#177]
I was building a deck intended for Cache Refresh. When I clicked on the box to check CR compliance, the builder stopped counting the influence of new cards I added to the deck. When I unchecked the box, the correct influence count showed up again.

This was on Google Chrome if that makes a difference.

**Comment by gereons** [comment]
Works for me again, now that Sovereign Sight has been marked as released. There's definitely a bug there, however, related to when a new cycle is added and none of its packs are released.
