### ISSUE TITLE
Wrong Cards in Deck list

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#178]
This one is a bit complicated and I'm not sure it is an issue anymore.

I've build a deck (ID 1053894) on 12-Dec which I used to play a tournament on the 17-Dec. Afterwards (all on the 17-Dec) I checked the deck to publish it, but it was corrupted. Instead of Weyland Titan it was now a Core NBN ID and instead of Project Atlas it contained Project Beal as an Agenda and some other wired stuff.
So I created the deck from the stratch and published it on NRDB https://netrunnerdb.com/en/decklist/47390/maze-titan
this was ok on 17-Dec, but now it's total wired, it's a titan Deck containing Nisei as an Agenda. No idea how to do this, so this seems to be an issue. The list in my private deck lists is now ok. So I'm not sure what kind of a mixup might have happened, but thought it would be good to report it.

Instead the correct list should be:
Titan Transnational: Investing In Your Future

Agenda (10)
3x Global Food Initiative  ●●●
3x Hostile Takeover
1x Merger  ●
3x Project Atlas

Upgrade (2)
2x Cyberdex Virus Suite

Operation (23)
3x Audacity
3x Beanstalk Royalties
1x Biotic Labor  ●●●●
2x BOOM!
1x Consulting Visit
2x Fast Track
2x Hard-Hitting News  ●●●●
3x Hedge Fund
2x IPO
2x Preemptive Action
1x Shipment from Tennin  ●●●
1x Special Report  ●●

Barrier (3)
3x Vanilla

Code Gate (5)
3x Enigma
2x Hortum

Sentry (3)
2x Guard
1x Sapper

Other (3)
3x Mother Goddess

17 influence spent (max 17, available 0)
20 agenda points (between 20 and 21)
49 cards (min 45)
Cards up to Revised Core Set

**Comment by x3N1GM4x** [comment]
Believe this is resolved now, as per #176.
