### ISSUE TITLE
Updating a deck description

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#179]
When you want to update your deck description a small box on the screan appears which is totally not sufficient to update the deck description.
* It's to small
* It doesn't support the card reference with #Cardname so you need to include it manually

**Comment by x3N1GM4x** [comment]
With regards to the size of that text box, you can drag it to be larger with the control in the bottom right corner:
![image](https://user-images.githubusercontent.com/10621139/49655793-89625880-fa33-11e8-9ed0-05f8914da1be.png)
As for adding `#card-name` support to that text box, is that different you what you've logged under #180?

**Comment by ghost** [comment]
Yes it is, as it's not working at all!
You can type "#" and whatever, but nothing is happening here. See Screenshot

![nrdb_edit](https://user-images.githubusercontent.com/5659287/49684279-31c6fa00-fad2-11e8-855b-97ff9d05b9a4.png)

**Comment by x3N1GM4x** [comment]
Ok, I'm with you, so it's just the #card-name functionality that remains to be resolved on this, you're happy that the field on the form can be resized?

**Comment by ghost** [comment]
Totally!

**Comment by plural** [comment]
This is fixed now with the new publish deck flows.
