### ISSUE TITLE
Add symbols in the Filter Help tooltip

### ISSUE THREAD

**Issue by Salem2612** [Null-Signal-Games/netrunnerdb#18]
Typing x:"[Recurring Credits]" allows to filter the cards that contain the Recurring Credits symbol. This is very helpful but I didn't find the list of the allowed symbols and the right words to put between [ ]. The list of these symbols is finally available in netrunnerdb/src/AppBundle/Service/CardsData.php private function backwardCompatibilitySymbols but it could be included in the Filter Help button when editing a deck.

Feature request : Add the list of the available symbols in Edit Deck > Build tab > Filter Help button > Smart filter syntax description  :
- [Subroutine]
- [Credits]
- [Trash]
- [Click]
- [Recurring Credits]
- [Memory Unit]
- [Link]

Thank you for this beautiful tool !

**Comment by alsciende** [comment]
Good idea. I have to update the frontend to use API 2.0, and that will change the text of the symbols. So when I update the frontend, I'll update the tooltip.

**Comment by Salem2612** [comment]
And could you add this Filter Help button in the card search page ? (https://netrunnerdb.com/find)

Maybe you could add it as a button at the left of the Search `<input>` in the same button group. Here in bold :

> `<div class="input-group" style="margin-bottom:.5em">`
>   **`<span class="input-group-btn"><button class="btn btn-default">Help</button></span>`**
>   `<input class="form-control" ... id="search-input" ...>`
>   `<span class="input-group-btn"><button class="btn btn-primary" type="submit">Search</button></span>`
> `</div>`

**Comment by yads** [comment]
How can we search for these keywords? Using x:[trash] does not seem to work

**Comment by alsciende** [comment]
@yads you have to enclose in double quotes: https://netrunnerdb.com/find/?q=x%3A%22%5Btrash%5D%22
