### ISSUE TITLE
database wont load

### ISSUE THREAD

**Issue by ra0uldukelives** [Null-Signal-Games/netrunnerdb#188]
![screen shot 2018-01-11 at 11 48 39 am](https://user-images.githubusercontent.com/35344209/34838602-9d6be97c-f6f6-11e7-9426-eff33541ac2f.png)

Not a developer, but I've been experiencing this issue with the site for a couple days. I've exhausted all my options on my personal machine, posting here in the event it's a broader issue.

**Comment by gereons** [comment]
I had a similar problem in Firefox a while ago, with the same messages about "xyz data is newer than database". Turned out Firefox' database for local storage was corrupted and I had to delete it completely. Maybe your Safari suffers from a similar problem?

**Comment by x3N1GM4x** [comment]
Are you still having this problem @ra0uldukelives or @gereons?

**Comment by gereons** [comment]
No, never happend again. I think this can be closed.
