### ISSUE TITLE
[Bug] Sorting Decklist by Faction Hides Minifaction Cards

### ISSUE THREAD

**Issue by CoryOwens** [Null-Signal-Games/netrunnerdb#19]
When sorting a decklist by Faction (by Faction, by Faction then Type, or by Faction then Set), the decklist will not display cards from the Data and Destiny runner mini-factions (Adam, Apex, Sunny Lebeau). 

![sortbuga](https://cloud.githubusercontent.com/assets/8702020/16711414/22eec03e-4617-11e6-8f7b-554e5c4587f4.JPG)
![sortbugb](https://cloud.githubusercontent.com/assets/8702020/16711415/254286ae-4617-11e6-9e73-8ab47babbbf2.JPG)
![sortbugc](https://cloud.githubusercontent.com/assets/8702020/16711416/27a07136-4617-11e6-926d-8e02f872e52f.JPG)
![sortbugd](https://cloud.githubusercontent.com/assets/8702020/16711417/292884a8-4617-11e6-87f1-fea831422373.JPG)

This issue has been confirmed to affect cards from all three mini-factions. This issue occurs regardless of deck ID (testest with Adam, Apex, Sunny Lebeau, and MaxX: Maximum Punk Rock).

**Comment by CoryOwens** [comment]
Issue should be fixed by commit 9d2f1a2690d1f3c7a6d11b5e9f629b79acade223 in pending pull request.

**Comment by alsciende** [comment]
Thank you Cory, nice work.
