### ISSUE TITLE
Publishing Decks with Reference

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#191]
When publishing a deck the reference is not asked, you need to do it via an update where you can enter the reference deck list. It would be nice when this would be possible when publishing the deck.

**Comment by x3N1GM4x** [comment]
I'm not totally clear on what you mean by "reference" in this context, could you elaborate a little, maybe provide some screenshots showing what you mean?

**Comment by gereons** [comment]
I believe this is the "this deck is based on XYZ" field, which has been set automatically since #123 landed.

**Comment by ghost** [comment]
I don't agree to this.

Yes it's about this deck is based on... 
But often People take a deck as a basis without just copying it. And thus the automatic link is not working (got the list throu stimhack or whatever).
In case it's empty it would be nice to show the reference when publishing a deck.
