### ISSUE TITLE
UFAQ entries for Aeneas Informant and Maw no longer correct for interaction with Salsette Slums

### ISSUE THREAD

**Issue by yads** [Null-Signal-Games/netrunnerdb#194]
The UFAQ ruling for Maw says:
>**If the Runner uses Salsette Slums to remove a trashed card from the game, does Maw trigger?**
No, Maw does not trigger. In order to use Salsette Slums, the Runner must trash the accessed card.

And for Aeneas Informant:
>**If the Runner uses Salsette Slums to remove a trashed card from the game, does Aeneas Informant trigger?**
No. In order to use Salsette Slums, the Runner must trash the accessed card.

Neither of these are true anymore since Salsette Slums has been errata'd to say:
>Once per turn, you may pay the trash cost of a card you access that is not in Archives to remove that card from the game.

**Comment by alsciende** [comment]
This data is not managed by me or by the repository. You would need to reach Jacob Morris (@jakodrako on twitter).

**Comment by yads** [comment]
Cheers I was trying to find where the data is.
