### ISSUE TITLE
The public deck API 2.0 endpoint redirects to a login page

### ISSUE THREAD

**Issue by frogamic** [Null-Signal-Games/netrunnerdb#2]
I'm migrating my app to the new API version and I discovered that any call to the public deck API redirects to an HTML login page, for example:
https://netrunnerdb.com/api/2.0/public/deck/35079
Edit: just tried _decklist_ in place of _deck_ and it works. Typo in the API docs?

**Comment by frogamic** [comment]
Now it just goes to a 404, while the decks are accessible at https://netrunnerdb.com/api/2.0/public/decklist/{deck-id}

**Comment by alsciende** [comment]
I can access the deck public API: https://netrunnerdb.com/api/2.0/public/deck/680381

**Comment by alsciende** [comment]
Didn't you simply try a deck_id that doesn't exist?

**Comment by frogamic** [comment]
My mistake, I didn't realise the difference between a _ published_ decklist and a _private, shared_ deck, the ID I was trying was a published decklist
