### ISSUE TITLE
Request - Be able to hide rotated cards in card search

### ISSUE THREAD

**Issue by percomis** [Null-Signal-Games/netrunnerdb#205]
Hello!

It would be really cool to somehow be able to hide the already rotated cards in Card Search. Could easily just be a checkbox or something or even just manually select which sets I'd like to look in.

Thank you!

**Comment by EnderAtreides** [comment]
Would be nice, but for now you can use "c!1 c!2 c!4" to negate Core, Genesis and Spin respectively.

**Comment by ladybunne** [comment]
@EnderAtreides I've been looking for a way to do this for weeks, thank you!!

**Comment by ladybunne** [comment]
FWIW `c!1|2|4` is a slightly more concise way of doing the same 😉
For Modded (Revised Core and the most current cycle) you can also do `c:20|21`! (Until Kitara is made obsolete by the next cycle)
