### ISSUE TITLE
Error 500 when duplicating decks

### ISSUE THREAD

**Issue by helanhalvan** [Null-Signal-Games/netrunnerdb#210]
Hi,

As of today, when trying to duplicate decks on my account, I get this error:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
```

I have tried doing it on multiple devices using different browsers. It also happens when I try to click on a lot of different other things. Listing the resulting URLS, so I get the same error when clicking to get to any of these locations:

https://netrunnerdb.com/en/deck/duplicate/1074604

https://netrunnerdb.com/en/search

https://netrunnerdb.com/en/deck/save

https://netrunnerdb.com/en/reviews

https://netrunnerdb.com/en/faction/criminal

I think there is something wrong with the data associated with my account, as before logging in, there was no problem. Also, it does not seem possible to log out, when I click the symbol to the right I get no drop down.

**Comment by jdcowf** [comment]
I'm also getting a 500 error when I try to access the faction tabs or search by an included card.

**Comment by Saracenus** [comment]
I am getting this error when I try to create a new Runner or Corp deck. 
I am running Chrome on Windows 10. I switched over to the Edge browser to make sure it wasn't Chrome acting up. No luck. 
This is also happening in Chrome on my iPad Pro Gen 2.
I am also unable to access my profile.
Accessing from Comcast in Portland, Oregon USA.
Bryan "Saracenus" Blumklotz

**Comment by potterness** [comment]
I can confirm this as well. Chrome Version 64.0.3282.186, Comcast from Illinois USA. It appears I can access My Decks just fine, including grabbing Jinteki.net format and all that, but if I try to make a new corp or runner deck it slaps me with the 500 internal server error. Hope this helps.

**Comment by x3N1GM4x** [comment]
I believe these issues were resolved at the time, please let us know if you are still experiencing them.
