### ISSUE TITLE
Account/Site/Deck Errors

### ISSUE THREAD

**Issue by Agent-Chezni** [Null-Signal-Games/netrunnerdb#211]
Hello,

NetrunnerDB interface is exhibiting several errors for me and a handful of others.
> Cannot access decks to edit them
> Logging in acts oddly (cannot click little head in top-right corner to log in/out)
> Many pages don't load, including individual card pages

Reddit thread here: https://www.reddit.com/r/Netrunner/comments/84594h/netrunnerdb_acting_strange/

As always, thanks for running NDB!
--Chezni

**Comment by x3N1GM4x** [comment]
I believe this was resolved at the time, but please do let us know if you're still experiencing any problems.
