### ISSUE TITLE
Icon for deleting published decklists missing 

### ISSUE THREAD

**Issue by madarasz** [Null-Signal-Games/netrunnerdb#215]
To reproduce:

1. Login to NetrunnerDB
2. Go to Decklists >> My decklists. Select a published decklist of user.
3. Observe icons on top right. 

There used to be two icons. A blue pen icon (edit) and a red trashcan icon (delete). The delete icon is missing, user cannot delete his/her published decklists. 

I know there was the delete icon there, I have autotests for publishing decks via Alwaysberunning.net and cleaning them up afterwards on NetrunnerDB. The test fails because it cannot find the button that used to be there.

**Comment by gereons** [comment]
AFAIT this line from `src/AppBundle/Service/PersonalizationHelper.php` is the culprit:

`$content['can_delete'] = ($decklist->getNbcomments() == 0) && ($decklist->getNbfavorites() == 0) && ($decklist->getNbvotes() == 0);`

i.e. you can only delete a published decklist if it has 0 comments, 0 likes and 0 upvotes.

**Comment by madarasz** [comment]
My published decklist did not have any comments, likes or upvotes and the trash icon was missing. Now the problem seems solved, closing this.
