### ISSUE TITLE
Cannot publish Reviews

### ISSUE THREAD

**Issue by EnderAtreides** [Null-Signal-Games/netrunnerdb#218]
The latest review is from March 23, so seems to be global. When I go to publish, I get "An error occured while posting your review (OK). Reload the page and try again." red text instead of a confirmation.

**Comment by alsciende** [comment]
Which card are you trying to review? I successfully posted one on Sweeps Week.

**Comment by EnderAtreides** [comment]
I was trying to review NEXT Sapphire, using Chrome. When I look at [the page of recent reviews](https://netrunnerdb.com/en/reviews) the most recent one that I can see is for Silhouette on 23 March 2018. Is that not the most recent review? The only review I see for Sweeps Week is from 28 Jan 2015 by tiedyedvortex, and the most recent comment on it is by Tsgstarwars on 28 Jun 2015. I also tried loading that page with Firefox (which I haven't used in a long time; same thing.)
![screenshot 2018-03-29 08 34 50](https://user-images.githubusercontent.com/25988197/38089050-2255acf6-332c-11e8-863a-ee694454cc6f.png)

**Comment by alsciende** [comment]
I removed my FAKE REVIEW as soon as it was published ;)

**Comment by alsciende** [comment]
I'll try to review NEXT Sapphire, see how it goes. Also I'll see if there are checks to prevent you from publishing a review. I can't remember off the top of my head, but maybe there's a reputation check.

**Comment by gereons** [comment]
I'm pretty sure this is related to emoji usage. For example, if a review text contains an emoji that is only expressible as a 4-byte unicode code point, such as "😂", the insert/update of the database fails with errors like `PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x82 B...' for column 'rawtext' at row 1` unless the database encoding is set to `utf8mb4`.

**Comment by alsciende** [comment]
@gereons Thank you! I applied the fix in prod.
