### ISSUE TITLE
[Bug] "Upload All Decks" Fails on OCTGN Files

### ISSUE THREAD

**Issue by CoryOwens** [Null-Signal-Games/netrunnerdb#22]
In "My Decks," using the "Upload All Decks" option with a .zip file containing OCTGN deck lists (.o8d), the server responds with the error

```
503 Service Unavailable
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

Feature works with .zip files containing plain text deck lists, as those downloaded from the "Download All Decks" feature. 

Related note: error message for uploading the wrong archive type, like a .rar file, is simply "Bad file" and could be improved.

Possible fixes: 
- Update upload archive feature to accept OCTGN files within the archive.
- Update upload archive feature to give a more useful error message when encountering unsupported file types.
- Update file selection modal to give more explicit instructions (sex: "Select a .zip file containing plaintext decklists").

**Comment by plural** [comment]
I'll do a little checking to see if any of the OCTGN support is still in use, but this is probably not going to get fixed.
