### ISSUE TITLE
Getting Many Unrelated Notifications

### ISSUE THREAD

**Issue by joemspalding** [Null-Signal-Games/netrunnerdb#220]
See image. I have no published decklists and all notifications are presumably turned off. I have not subscribed to any creators if memory serves me. Is there a reason why this could be happening?

![image](https://user-images.githubusercontent.com/25623615/38253679-41c7f222-3725-11e8-9a6e-ddfc3e47ae43.png)

**Comment by x3N1GM4x** [comment]
See @archmage's comment on #227:

> If you don't follow anyone, NRDB acts as if you follow everyone. If you follow yourself, you'll no longer receive these notifications, except when you post things. Maybe create a dummy account and follow it on your main to stop them entirely?
