### ISSUE TITLE
Images for The Devil and the Dragon are pointing at netrunnerdb instead of cardgamedb

### ISSUE THREAD

**Issue by yads** [Null-Signal-Games/netrunnerdb#225]
It looks like all of the cards from The Devil and the Dragon are pointing to netrunnerdb (e.g. https://netrunnerdb.com/card_image/21061.png). Since NRDB has changed to using cardgamedb for its images these should be updated. It doesn't look like this data is stored in the https://github.com/Alsciende/netrunner-cards-json/ repo though.

**Comment by haradan** [comment]
This is causing there to be no images for the set in either netrunnerdb.com or in the API. How do they get updated usually when they need to point to cardgamedb?

**Comment by haradan** [comment]
I did notice the cardgamedb images for this set have a different filename format from previous sets, maybe that's causing a problem with the integration?

Previous cardgamedb images used in netrunnerdb have filenames in the format **med**\_ADN[setID]\_[cardNumber].png, whereas The Devil and the Dragon has filenames in the format **ffg**\_ADN[setID]\_[cardNumber].png.

**Comment by haradan** [comment]
Yes, that seems to be the problem. The cardgamedb images are autogenerated with the old format here:

https://github.com/Alsciende/netrunnerdb/blob/70e6c177967a270c4faae9d07fc935070f1a7a45/src/AppBundle/Command/ImportImagesCommand.php

**Comment by haradan** [comment]
Just deleted some posts suggesting it might have been a problem with a change in the filename formats. The previous filename format still works so that's not it.

**Comment by haradan** [comment]
It looks like the image import from cardgamedb might need to be run manually. Maybe this can be automated to run regularly?

https://github.com/Alsciende/netrunnerdb/blob/70e6c177967a270c4faae9d07fc935070f1a7a45/src/AppBundle/Command/ImportImagesCommand.php

**Comment by yads** [comment]
Looks like this has now been fixed. Closing out.
