### ISSUE TITLE
Cycle code for "Reign and Reverie" in cycles and packs API do not match

### ISSUE THREAD

**Issue by madarasz** [Null-Signal-Games/netrunnerdb#226]
Look up the *code* of "Reign and Reverie" in the cycles API, it's **rar**
https://netrunnerdb.com/api/2.0/public/cycles

Look it up the *cycle_code* of "Reign and Reverie" in packs API, it's **reign-and-reverie**
https://netrunnerdb.com/api/2.0/public/packs

These two should match. Probably the cycles API value should be changed, as it's not abbreviated for other cycles (eg. data-and-destiny, honor-and-profit)

**Comment by alsciende** [comment]
Thanks. It's now fixed.
