### ISSUE TITLE
Unusual amount of notifications (activity)

### ISSUE THREAD

**Issue by HornedRat** [Null-Signal-Games/netrunnerdb#227]
For some time I have a very large number of notifications. The activities I am notified about include users I never followed commenting on cards I never browsed
![nrdb activity](https://user-images.githubusercontent.com/29658388/40228443-9d36c716-5a91-11e8-90a6-7069a2c757bd.png)

**Comment by ladybunne** [comment]
If you don't follow anyone, NRDB acts as if you follow everyone. If you follow yourself, you'll no longer receive these notifications, except when you post things. Maybe create a dummy account and follow it on your main to stop them entirely?

**Comment by x3N1GM4x** [comment]
Duplicate of #220, and has been answered by @archmage above.
