### ISSUE TITLE
[Bug?] Progress bar in deck history just ticks down, doesn't seem to signify anything.

### ISSUE THREAD

**Issue by beardsley-james** [Null-Signal-Games/netrunnerdb#23]
There's a blue progress bar when I'm looking at my deck history. It decreases, slowly but steadily, empties, and then resets to full to continue the cycle. I watched it for way too long and I am not sure what it is supposed to signify.

**Comment by CoryOwens** [comment]
That bar shows the autosave interval. If you make changes to the deck, but do no hit the save button, when that blue bar reaches zero you'll see your changes added to the history.

**Comment by beardsley-james** [comment]
That makes sense, maybe there should be a tooltip or it should be less obtrusive? It's kind of ominous.

**Comment by CoryOwens** [comment]
Yeah, I could agree with that. The only way I was able to figure out what it did was by reading the code.

**Comment by beardsley-james** [comment]
Yeah, [here's](https://github.com/Alsciende/netrunnerdb/blob/master/src/AppBundle/Resources/views/Builder/deck.html.twig#L258) the HTML for it. Looks like it's using bootstrap but tooltip is a specific plugin that's not in there right now. Maybe take out the "sr-only" tag on the caption and make it say "Time remaining to autosave" would be the easiest way, or just take it out altogether since it doesn't really add anything.

**Comment by alsciende** [comment]
Agreed, it's useless. I removed it.
