### ISSUE TITLE
Password reset not sending email

### ISSUE THREAD

**Issue by slosscyr** [Null-Signal-Games/netrunnerdb#232]
I've tried numerous times to reset my password but nothing appears to get sent.  The address is Gmail, I've checked all the usual culprits for mail diverted as spam/junk, but cannot find an instance of a pw reset being sent.

The account is quite old and has been inactive for a while; don't know if that would make a difference or not.

Thanks,

**Comment by x3N1GM4x** [comment]
Re-reported by some users in Slack - we should try to look into this when we can.

**Comment by wilcornish** [comment]
Continues to be an issue, I have now lost account access.

**Comment by NoahTheDuke** [comment]
I’ll take a look in the morning. I don’t know much about how the system works but I should be able to figure out how to make something happen for everyone.

**Comment by slosscyr** [comment]
I have yet to be able to access the account in the original post.  The problem has gotten worse for me on the computer I'm currently using; so far tonight, I've tried resetting passwords for 4 different accounts, including 2 created just to test, with no luck.  I've been using hotmail, gmail, and yahoo for the accounts and chrome and edge for the browsers. Clearing cache did not seem to remedy.

**Comment by gannicottb** [comment]
My use case is less severe - just want to delete an old account, but need to reset password before I can log into it.

**Comment by Simplician** [comment]
I am also having this problem. I'm coming back to Netrunner after quite a break and would like to use the deckbuilder, but I can't get an email to reset my account. And of course I can't make a new account because my email is already in the system.

It's a Gmail, I also checked the Spam folder, nothing. I've tried multiple times in the last few months.

**Comment by NoahTheDuke** [comment]
There’s no email server set up on NRDB right now. That’s why no one is getting emailed. We are working on adding it back but it’s more complicated than expected.

**Comment by x3N1GM4x** [comment]
This should now be resolved, as an SMTP server has been set up and SPF and DKIM configured.
