### ISSUE TITLE
[Feature] Custom sorting patterns and "My Collection"

### ISSUE THREAD

**Issue by beardsley-james** [Null-Signal-Games/netrunnerdb#24]
These are different things but they'd both be covered by additional information stored in user accounts. The LotR database NRDB is based off of has a "my collections" option where you can store information on what adventure packs you currently own. While many people own all or very few of the cards, I imagine many people are like myself in the process of building a collection and I wish my searches would default to decks/cards that are currently accessible to me.

Also, I store my cards in binders and a lot of other people do too, and my sorting patterns don't exactly match the order defaulted to by "Faction, then type". It's not critical but it would be convenient, for indexing, if I could choose what order the factions and types were in for that sort option.

With these two features, you could print/save an index following your sorting preferences that you could use to better navigate a physical collection of cards, or alphabetize an existing collection.

**Comment by alsciende** [comment]
I won't do the custom sorting patterns, sorry, but "My Collection" is such a great idea, I've wanted to do the same thing since it's been added to RingsDB. (btw, NRDB isn't based off RingsDB, it's the other way around.)

**Comment by yupferris** [comment]
I would love a "my collection" feature

**Comment by x3N1GM4x** [comment]
"My Collection" has been implemented for some time now, so closing this issue.
