### ISSUE TITLE
Internal Server Error 6 sept.

### ISSUE THREAD

**Issue by oskarkv** [Null-Signal-Games/netrunnerdb#240]
Whenever I use https://netrunnerdb.com/en/decklists/search and search for a deck with a specific card, I get 500 Internal Server Error. Started today, about the time I posted this issue.

**Comment by oskarkv** [comment]
And just trying to go to https://netrunnerdb.com/en/search gives me internal server error too.

**Comment by Sesostrismage** [comment]
I get the same if I try to create a new deck, or edit and save an existing deck.

**Comment by tucker87** [comment]
Same issue on Importing as well.

**Comment by oskarkv** [comment]
Seems to have been resolved now.

**Comment by alsciende** [comment]
Thanks guys
