### ISSUE TITLE
cardgamedb image requests timing out due to https instead of http

### ISSUE THREAD

**Issue by ejpeeZ** [Null-Signal-Games/netrunnerdb#242]
As always, feel free to remove this if it's just me. I am on Chrome.

It seems that (some?) requests made to cardgamedb time out if they are done via `https//`

It seems that requests changed from http to https in this PR https://github.com/Alsciende/netrunnerdb/pull/203

For example:
http://www.cardgamedb.com/forums/uploads/an/med_ADN49_72.png works, 
https://www.cardgamedb.com/forums/uploads/an/med_ADN49_72.png does not.

In that PR this change was made to prevent "mixed content warnings". I'm not exactly sure if changing back to `http://` to show images outweighs the need to prevent such warnings, but I'll make a tiny PR nonetheless (I can't really setup the testing environment).

**Comment by ejpeeZ** [comment]
Though I do wonder what changed, seemed to be working before 🤔 . Perhaps I should have checked at Cardgame.db.

**Comment by x3N1GM4x** [comment]
Looks like this was resolved with #243? I cannot reproduce in production and in fact can see card images from cardgamedb over https within NRDB. Closing unless someone can reproduce an issue.

**Comment by ejpeeZ** [comment]
Yeah well I only switched the links to `http://`, when it was merged the import job wasn't run yet I think. But yes all sets have images now, so this issue is fixed and rightfully closed.
