### ISSUE TITLE
No email after reset password

### ISSUE THREAD

**Issue by Ligaze** [Null-Signal-Games/netrunnerdb#249]
I will come back to netrunner and ive forgot my password but the reset password doesn't send email (i check the spam folder )

**Comment by x3N1GM4x** [comment]
This looks like a duplicate of #232. Suggest we close and combine.

**Comment by NoahTheDuke** [comment]
Agreed.

**Comment by x3N1GM4x** [comment]
#232 has now been resolved, so password reset emails should be working again.
