### ISSUE TITLE
Wrong trash cost in search results

### ISSUE THREAD

**Issue by Absotively** [Null-Signal-Games/netrunnerdb#251]
In search results displayed as a checklist, the trash cost of the Revised Core Set's Snare! is displayed as 6, rather than 0. It is correct in the card data, and it is displayed correctly on the card page and in search results displayed as spoilers.
![nrdb_trash_cost_in_search_results_bug](https://user-images.githubusercontent.com/7109803/48239339-b87d9f80-e38b-11e8-8362-11d0db8aaa05.png)

**Comment by NoahTheDuke** [comment]
Oh that’s interesting. Thanks so much! I’ll look into it.

**Comment by Smashman** [comment]
How peculiar! The card data shows the right cost.

https://github.com/Alsciende/netrunner-cards-json/blob/master/pack/core2.json#L1773

**Comment by Absotively** [comment]
Can't reproduce this on my local instance.

**Comment by NoahTheDuke** [comment]
There was an error in the database which I have corrected, fixing this issue. I don't know where the error came from (RevCore Snare! having strength 6), so I can't promise future errors like it won't pop up but the fix was relatively easy, so I'll close this as fixed.

**Comment by Smashman** [comment]
Cool. I was going to theorise that the database had a strength or agenda point value. I'll keep an eye out for any other weird things. 

Maybe the database should have some validation ensuring that those values can only be set if it's a valid card type?

**Comment by NoahTheDuke** [comment]
That's a goal of ours, but I don't know enough about how the overall system works yet to make any real suggestions on implementation. If you know anything about PHP, I'd love to hear your thoughts!
