### ISSUE TITLE
Cards from System Core 2019 break the decklist search results

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [Null-Signal-Games/netrunnerdb#259]
If you're looking for a deck that contains a card that is present in System Core 2019, there's no results, even if you choose an instance of this card that comes from previous packs (I've cross-checked the ids). Apparently, it doesn't seem to be a problem with multiple copies/instances of a card with a same name - for example, if you look for a deck containing Demolition Run (present in core and revised core, not present in SC2019), results are returned properly.

To reproduce:
Search for a deck containing Femme Fatale. There are three versions hinted (core, revised, system core), but no matter which one you choose, it returns 0 results.

**Comment by binarymelon** [comment]
I did some investigation on this and it seems like the typeahead for the cards field only ever selects the most recently released version of the card (and as a result only ever searches for decks with that version of the card).  You'll notice that the Demolition Run search only seems to return results from roughly the last year.

You can see the difference between these two searches (card 20002 is the revised core version of Demolition Run and 01003 is the original).
https://netrunnerdb.com/en/decklists/find/2?faction=&cards[0]=20002
vs.
https://netrunnerdb.com/en/decklists/find/2?faction=&cards[0]=01003

**Comment by NoahTheDuke** [comment]
Ah heck, okay. I’ll take a look!

**Comment by binarymelon** [comment]
@NoahTheDuke Sent you a message on slack regarding a possible fix.

**Comment by x3N1GM4x** [comment]
This is now fixed in production, source control will be tidied up later accordingly.

**Comment by Transistor0** [comment]
I'm finding that if you select Quetzal you get two options of name but both come through as the Core 2019 version and no decks get listed (even though I know there are loads!). Same applies for Leela Patel.

**Comment by binarymelon** [comment]
@Transistor0 Could you try clicking the 'Clear data' link at the bottom of the page and try again.
