### ISSUE TITLE
1.1.1.1 and Cache Refresh legality checks seemingly inconsistent

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#264]
Identified while checking #258.

If you create a deck and include a card from a rotated core set, it causes the Cache Refresh legality check to (correctly) fail, but remains legal according to the 1.1.1.1 validation - is this right?

![image](https://user-images.githubusercontent.com/10621139/49385858-37a98d80-f716-11e8-9898-9276025a1114.png)
My understanding is that 1.1.1.1 should require the latest Core, just like Cache Refresh appears to. 

Might be a slightly grey area as neither format is 100% explicitly and consistently defined. I've seen different versions of both in  use.

**Comment by NoahTheDuke** [comment]
My understanding was that Cache Refresh is defined as the most recent Core, Terminal Directive, 1 Big Box, and the 2 most recent cycles (currently Kitara and Red Sands), and 1.1.1.1 is a single copy of any core set, 1 big box, 1 data pack, and 1 card playset. Using an older core is okay as long as you don't also use cards from the new core.

Previously, 1.1.1.1 was written to be core agnostic, and I’m okay with that. If we want to enforce it differently, that’s okay too.

**Comment by x3N1GM4x** [comment]
Yeah, that makes sense actually, not sure why I thought there was a problem. 😄
