### ISSUE TITLE
[Feature Request] MWL and Formats pages

### ISSUE THREAD

**Issue by chaosof99** [Null-Signal-Games/netrunnerdb#266]
It would be very good to have a dedicated page to host explanations and lists of what the individual MWLs consist of. The feature of switching between various MWLs in a decklist page is good, but nowhere on the site is explained what those MWL options actually mean, which is particularly annoying for newbies or returning players.

The MWL page could be similar to the rules and rulings pages with an index on the side, and should list separate entries per MWL in reverse chronological order (so the most recent is on top so it is the first seen when visiting the page). Each MWL entry should explain the system used (universal influence vs. banned/restricted), the start and end date of when it was in effect, the decision makers (FFG/NISEI) and of course a list of cards and how they were segmented. The cards should of course by hyperlinked with mouse-over cardtext. Perhaps the page could also have entries rotations in a similar fashion, listing what sets were removed from legality.

Furthermore I would suggest adding an info-icon to the MWL menu in the decklist pages linking to the MWL page. I would also suggest to put together the new MWL page as well as the Rules and Rulings page in a new drop-down menu in the header bar called "Resources" or similar.

Another page in the Resources page should be a Formats page, which should list all the tournament formats supported by NISEI (and possibly older ones), what they consist of as well as the current set legality and the active MWL for that Format.

**Comment by x3N1GM4x** [comment]
In case you didn't know, the details of all currently supported NISEI formats, with their cardpools and MWLs is [here](http://nisei.net/op/supported-formats) on the NISEI website.

However, this doesn't mean we couldn't do more on NRDB to make the different formats and MWLs more accessible - it's certainly something which is already planned for the future.

**Comment by plural** [comment]
Fixed a few months ago.

MWL/Ban list page: https://netrunnerdb.com/en/banlists
Format (at least for Standard and Startup): https://netrunnerdb.com/en/formats
