### ISSUE TITLE
Searching for programs based on memory usage

### ISSUE THREAD

**Issue by s3689650** [Null-Signal-Games/netrunnerdb#276]
On the about page in the search syntax criteria is the **m** criteria for searching programs by their memory usage. It only seems to function when used with the **!** operator.

I would appreciate it, if it could be extended to use all operators or failing that a note be made on the about page about its supported usage for clarity.

**Comment by gereons** [comment]
Works for me: https://netrunnerdb.com/find/?q=m%3A2

**Comment by NoahTheDuke** [comment]
[CardsData.php](https://github.com/Alsciende/netrunnerdb/blob/1e5f79365af9a58f7408f876db838fc72e79e99a/src/AppBundle/Service/CardsData.php#L771): Looks like `m` is not listed as a Numeric condition, so it doesn't accept `>` or `<`. I'll add it to a PR.
