### ISSUE TITLE
Context sensitivity when entering card names not working

### ISSUE THREAD

**Issue by Transistor0** [Null-Signal-Games/netrunnerdb#298]
When you start to type the name of the card in the 'Cards Used' field in 'Decklist Search', you no longer get options for possible cards coming up. I've tried clearing data but that's made no difference.

**Comment by NoahTheDuke** [comment]
Damn, you tried today? I thought I caught the last bug. Try clearing the cache for NetrunnerDB. And see if that works

**Comment by gannicottb** [comment]
Just tried the typeahead today, I think these JS errors are relevant:

![screen shot 2019-01-11 at 12 13 09 pm](https://user-images.githubusercontent.com/894755/51051781-6713ab80-159a-11e9-9a59-b4138cfbccce.png)

I tried clearing the cache to no effect (Empty Cache and Hard Reload in Chrome).

**Comment by Transistor0** [comment]
Hi.
I've just tried it and it seems to be working!

Big thanks cos I can continue to get my netrunner deck fix!!

Steph xx

Sent from my iPhone

On 11 Jan 2019, at 16:27, Noah <notifications@github.com<mailto:notifications@github.com>> wrote:


Damn, you tried today? I thought I caught the last bug

**Comment by gannicottb** [comment]
I only get this issue on desktop (two different machines, as well). Typeahead works normally on mobile. I've cleared the cache, logged in/out, no change.

**Comment by Transistor0** [comment]
Yes, same here. My iPhone works fine but Microsoft Edge doesn't and I've tried clearing cache as well.

Sent from my iPhone

On 12 Jan 2019, at 16:09, gannicottb <notifications@github.com<mailto:notifications@github.com>> wrote:


I only get this issue on desktop (two different machines, as well). Typeahead works normally on mobile. I've cleared the cache, logged in/out, no change.

**Comment by NoahTheDuke** [comment]
Is anyone still experiencing this? I implemented a fix early last week but want to make sure I've not missed anything.

**Comment by gannicottb** [comment]
It's fixed for me on mobile and desktop. Thanks so much!

**Comment by NoahTheDuke** [comment]
You're welcome!

I'm gonna close this for now, but please comment if this comes up again, any of you. I really want to keep this fixed.

**Comment by Transistor0** [comment]
It's been working fine for me for some time. So I think it's ok to close.
Thanks for asking.

Regards

Steph

Sent from my iPhone

On 8 Feb 2019, at 20:35, Noah <notifications@github.com<mailto:notifications@github.com>> wrote:


Is anyone still experiencing this? I implemented a fix early last week but want to make sure I've not missed anything.
