### ISSUE TITLE
Custom rotation/card pool

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#301]
Would be nice to have the option to customize your own cardpool/rotation, that is, decide which cards from an expansion is in your cardpool. 

Now that the official A:NR is dead, it would be a great option for new casual leagues/players to shop around and decide how to expand their cardpool and meta (such as myself). Maybe I want to add a few NBN cards from the original Core into the pool, but not any other rotated cards. Maybe I want to add just the corp cards from Terminal Directive, but not the runner cards.

It could be done by adding the option to include/exclude single cards under 'collection' in the edit menu.

AMAZING site. Thanks for your work. Couldn't imagine building decks without this tool!

**Comment by ghost** [comment]
Woups. This feature request has already been asked her https://github.com/Alsciende/netrunnerdb/issues/246

**Comment by x3N1GM4x** [comment]
Now worries, will close this one as a dupe to keep things tidy - thanks for the feedback though!
