### ISSUE TITLE
Sorting card search results by Set not handling Cores correctly

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#305]
If you search for cards and have results including cards from multiple core sets, they are not being ordered correctly:
![image](https://user-images.githubusercontent.com/10621139/51533042-ad3dfa00-1e39-11e9-98c8-b1c9f71ba62a.png)
My best guess from this example without looking at the code is they're being sorted by the card id of the earliest version of the card?

**Comment by NoahTheDuke** [comment]
They’re sorted by the sql call which fetches all versions and then the old versions are dropped in php. We’ll probably have to move the sorting logic out of sql and into php.

**Comment by x3N1GM4x** [comment]
I haven't had a chance to look at the SQL yet, but wouldn't it be possible to sort first by set release date (of the most recent set which the card appears in, i.e. the one that gets tagged against it in the Set column of the results), meaning we can get the right sort without having to move it from the SQL query to PHP?

**Comment by NoahTheDuke** [comment]
Probably! At the end of `get_search_rows` in CardsData.php, you’ll find a switch statement that handles all of the sorting stuff. I bet not much would break if you added `->addOrderBy('y.date_release')` or whatever the column is named.

**Comment by x3N1GM4x** [comment]
> not much would break

Famous last words! I'll have a look when I have a min spare, unless someone else beats me to it. 😄
