### ISSUE TITLE
Sort on Build tab of Deckbuilder page doesn't work

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#306]
Clicking the column headers doesn't seem to do anything any more:

![image](https://user-images.githubusercontent.com/10621139/51753107-e7650100-20b0-11e9-9d78-68f321500c26.png)

Tested on all columns, both Chrome and Firefox, two different users.

**Comment by gannicottb** [comment]
This has been a bug for me for a few weeks now. The column I use the most is the Influence column.

**Comment by plural** [comment]
I tracked down the source of this error to the filtering to the latest version of a card.  

I'll try to get a patch out in the next day.

**Comment by plural** [comment]
i introduced a bit of a weird problem with the first version of this fix. 

https://github.com/Alsciende/netrunnerdb/pull/323 should take care of it for real.

Thanks to @NoahTheDuke for pointing this out to me this morning!
