### ISSUE TITLE
Images for 23 Seconds already available in the CGDB deckbiulder

### ISSUE THREAD

**Issue by zer0vect0r** [Null-Signal-Games/netrunnerdb#31]
I noticed that the images for 23 Seconds are not yet available on FFGAPP and I guess that's where you normally pull them from. Just wanted to inform you that they are already up on http://www.cardgamedb.com/index.php/androidnetrunner/android-netrunner-deckbuilder
When you select a card it displays in the center in the standard 300x419 resolution. Just have to set up the filter first.

**Comment by lostie** [comment]
They seem to be all available through: http://www.cardgamedb.com/forums/uploads/an/med_ADN36_<#X>.png

What is required to add them to the netrunnerdb server?
