### ISSUE TITLE
Run SuggestionsCommand to repopulate suggested cards

### ISSUE THREAD

**Issue by natthew** [Null-Signal-Games/netrunnerdb#313]
Can a netrunnerdb admin run the SuggestionsCommand (https://github.com/Alsciende/netrunnerdb/blob/master/src/AppBundle/Command/SuggestionsCommand.php) to repopulate the suggested card matrix?

**Comment by NoahTheDuke** [comment]
Sure! I'll do that now.

**Comment by natthew** [comment]
Amazing, thank you!
