### ISSUE TITLE
Published Decks by User has inconsistent paging

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#316]
I have 53 published decks. 
https://netrunnerdb.com/en/decklists/find?author=5N00P1
so more then one page is used for this. But when going to page 2, I might see the same decks as on page 1 and going back to page 1 it might look different then before. So it's hard to find some decks ;-)

I would say, the sorting algorithm is not reliable enough to always produce the same results. Which for me when looking for a deck and recomend it to some one is an issue.
Please see screenshots from page 1 before & after reload.
![snap1](https://user-images.githubusercontent.com/5659287/52861078-a3a26c00-3131-11e9-9b3a-6d48829c9c91.png)
![snap2](https://user-images.githubusercontent.com/5659287/52861085-aa30e380-3131-11e9-9b11-34fb25875050.png)

**Comment by NoahTheDuke** [comment]
Thanks for letting us know! Those screenshots are great. I'll take a look!
