### ISSUE TITLE
Update competition rules and include "Most Wanted" list

### ISSUE THREAD

**Issue by yupferris** [Null-Signal-Games/netrunnerdb#32]
See https://images-cdn.fantasyflightgames.com/filer_public/73/bf/73bf6fd3-de0e-4d1f-88ac-5a690e9ab08f/adn_tournament_rules_v302.pdf and https://images-cdn.fantasyflightgames.com/filer_public/e5/b5/e5b567d5-2873-4731-b2b6-5d3020b2bb02/adn_tournament_regulations_v113.pdf, for example

**Comment by plural** [comment]
closing this out since [NISEI.net](www.nisei.net) is now hosting the MWL information and there are multiple legality checkers implemented.
