### ISSUE TITLE
API is returning two versions of Downfall

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#320]
After Downfall was updated in the `packs.json` to change the name from "Ashes: Downfall" to just "Downfall", the API is returning both versions:

https://netrunnerdb.com/api/2.0/public/packs

I assume that despite the correct `packs.json` being on the server and the new version clearly having been loaded, the previous, incorrect version remains in the database or something?

**Comment by NoahTheDuke** [comment]
Yep, sounds like it! Time to fire up the sql!

**Comment by NoahTheDuke** [comment]
Fixed! Good looking out.
