### ISSUE TITLE
card navigation isn't working for ashes cards

### ISSUE THREAD

**Issue by plural** [Null-Signal-Games/netrunnerdb#326]
the spoiled cards for Ashes don't always show the card navigation at the top of the page:

![screenshot 2019-02-26 at 12 02 06 am](https://user-images.githubusercontent.com/396562/53390752-d6323d00-3959-11e9-92d7-8ab36cdfa841.png)
![screenshot 2019-02-26 at 12 02 30 am](https://user-images.githubusercontent.com/396562/53390758-dc281e00-3959-11e9-827f-e352b974bf05.png)

**Comment by NoahTheDuke** [comment]
Ah, that’s cuz it relies on sequential card positions.
