### ISSUE TITLE
New errata restrictions make it impossible to build some decks in limited formats.

### ISSUE THREAD

**Issue by mykonian** [Null-Signal-Games/netrunnerdb#33]
Obviously talking about astro right now. Even putting the deck legality to casual doesn't allow you to build a core-only NBN deck with your wonderful deckbuilder. 

I get this overlaps with people making casual decks with the current cardpool where the limitation is wanted, and I don't know the perfect solution. But maybe you do!

**Comment by alsciende** [comment]
Sadly, I don't either. I think it's FFG's role to solve this situation. If they decide that the errata is not applicable in a core-only deck, then I will adapt the deckbuilder. 

My advice: include another agenda and pretend it's Astroscript.
