### ISSUE TITLE
Please add the Worlds 2015 Runner and Corp expansion packs to the deckbuild "sets" selection

### ISSUE THREAD

**Issue by shrike311** [Null-Signal-Games/netrunnerdb#34]
In the deck builder portion of the website, where you can check the sets that you own (that determine what cardpool is viewable to build decks from) please add the newly released Worlds 2015 Runner deck and Worlds 2015 Corporation decks.  See https://www.fantasyflightgames.com/en/news/2016/1/11/run-like-a-champ/

By making those two expansion packs selectable in the "sets" button, although I do now own those two expansion packs but not some of the data packs those cards in the Worlds expansion packs originally were released in, I can still view the cards while deckbuilding.

Thank you and I would like to say Netrunnerdb is awesome!

**Comment by sheldonaj** [comment]
+1

**Comment by FurinjiGitHub** [comment]
+1

**Comment by alsciende** [comment]
Unless I'm mistaken, those decks are https://netrunnerdb.com/en/decklist/28867/test-run-ep-9-world-championship-foodcoats and https://netrunnerdb.com/en/decklist/30178/valencia-dlr

I'm going to try and find a way to resolve this issue.

**Comment by gereons** [comment]
+1 as well.
Assuming FFG will continue printing champion decks, these could go into a special "cycle", much like the draft IDs. This "champion-decks" cycle could have (pseudo) packs "2015-worlds-runner" and "2015-worlds-corp" - This would allow us to maintain these easily in the cards repo.

**Comment by alsciende** [comment]
Unfortunately, cycles and packs are not fit for this, since one card can only belong to one pack at the moment.

I'm thinking of adding a new entity "prebuilt" for these. That will let met display them in a special section in the site.

**Comment by gereons** [comment]
Ok, with a separate new API endpoint to get them I assume? That'd be great also, especially since those prebuilt collections would only need to consist of code/quantity pairs.

**Comment by alsciende** [comment]
Sure

**Comment by alsciende** [comment]
Done and done. The prebuilds can be listed in the Cards section, they can be included in the new Collection tab in the builder, and the API http://netrunnerdb.com/api/2.0/public/prebuilts has been added.
