### ISSUE TITLE
Nickname of Cards

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#342]
It would be nice to have the "official" nick names of cards listed here. So they could appear in search and for new players to see and learn them.
Like "Kitty" for QPM or "Baby" for "Symmetrical Visage"
Sure this is an enhancement that might not have priority.

**Comment by gereons** [comment]
Just to add to the idea, I do a similar thing in Net Deck. There's a list of hard-coded aliases like Kitty and Baby, and I also generate aliases from the first letters of each word (if there's more than one), so things like QPM or SMC Just Work™️
