### ISSUE TITLE
Clarification needed for bolding in advanced search syntax

### ISSUE THREAD

**Issue by mo0man** [Null-Signal-Games/netrunnerdb#346]
It doesn't say that searching for bolded text requires you to search for "<strong>AI</strong>"

**Comment by NoahTheDuke** [comment]
Thanks, that’s a good point. I’d love to have it skip over the xml elements, but currently haven’t found a means of doing so

**Comment by mo0man** [comment]
Sorry, I didn't mean that you need to change too programmatically in the search (I understand it could get complicated), but in the syntax reference page found [here](https://netrunnerdb.com/en/syntax) could you include a tip like "searching for bolded words within text might require you to search using `"<strong>AI</strong>"` and searching for icons should be bracketed, like [credit]"

**Comment by NoahTheDuke** [comment]
No worries! That’s going to be my currently solution, but it is good to think towards the future about how to fix it long term.

**Comment by mo0man** [comment]
Thanks!
