### ISSUE TITLE
Add link to ABR

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#353]
ABR (https://netrunnerdb.com/en/profile/18163/5N00P1) has a nice profile page (e.g. https://alwaysberunning.net/profile/18163) with a field where you can enter your NRDB User name and it will create a link to your NRDB profile page (e.g. https://netrunnerdb.com/en/profile/18163/5N00P1)
It would be nice when the profile page of NRDB would have the same linking back to ABR.
The ideal implementation would be a new field in the account page where you can enter your username and it will appear with link to the profile page of ABR.
The ABR implementation is easy and slim.
It should be optional so the people sign actively in.

**Comment by NoahTheDuke** [comment]
This is a great idea! I’ll look into it.

**Comment by plural** [comment]
There is now a link to the ABR profile if one exists (see #399)
