### ISSUE TITLE
Cannot add Zer0 card to deck

### ISSUE THREAD

**Issue by francescopellegrini** [Null-Signal-Games/netrunnerdb#359]
Hi,
I'm trying to add [Zer0](https://netrunnerdb.com/en/card/21101) to my deck, but the editor only shows the `0` selector.
No other cards are affected by this bug, at least in my collection.
Any thoughts?

**Comment by plural** [comment]
Zer0 is a banned card from MWL 2.2 through the current MWL.  If you have one of those MWL versions selected, you will only see the 0 option.  If you choose casual play or an earlier MWL you will be able to add 0-3 copies to your deck.

Would you please double-check if that explains your issue and let me know if that explains it for you?

**Comment by francescopellegrini** [comment]
You're correct. Sorry for the inconvenient, keep up the good work!

**Comment by plural** [comment]
It's no inconvenience at all!  Thanks for the report.  Happy running!
