### ISSUE TITLE
Faction buttons in search do not function

### ISSUE THREAD

**Issue by buzard49** [Null-Signal-Games/netrunnerdb#36]
I keep getting all factions if I search for something like Jintek ICE. I get all ICE from all factions. Same for Upgrades..etc.

**Comment by alsciende** [comment]
Can you describe what you are doing exactly? What is your locale?

**Comment by buzard49** [comment]
I think I finally figured it out. I had another button in wrong position. I
think.

**Comment by buzard49** [comment]
OK, that did not work. What I am trying to do is get a list of Jinteki ICE.

 I am leaving the title, text and flavor text blank. I am selecting the
CORP button (which turns gray) at this point all the faction buttons are
gray as well. I have tried both , clicking on jinteki only (it turns white)
and clicking on all but jinteki (it is the only gray button) and select
"ICE" as type. everything else is left "any" or blank. And the results for
both ways are the same, a list of "all" ICE.

About the only thing I have found that I can almost use is at the bottom
using the "by faction" option to have the entire list sorted by faction.
But it is a random list and the jinteki ice can't be sorted in any manor.
So I'm not sure what I am doing wrong. I'm selecting "corp" I've tried both
clicking only on jinteki and clicking on everything except jinteki on the
faction buttons, and selecting "ice" as type. So I'm not sure if I just
can't figure out how to do this (every other type of search I do works) or
I found a hole in the software. I wanted a list of just jentki ice that I
could sort different ways for comparison. I'm in California.

**Comment by buzard49** [comment]
I found the problem. For some reason CHROME can not use the search that
way. It won't work for "text" search either. I switched to IE and
everything is fine. W10, new computer. I'm in California.

**Comment by alsciende** [comment]
Ok, thank you for the explanation. It's useful.

~~Now, can you tell me what happens when you click "Search", after you selected "ICE" and clicked on the buttons to have only "Jinteki" and "Corp" selected?~~

**Comment by alsciende** [comment]
I assume by your explanation that your form looks like that, right?

![capture d ecran 2016-08-18 a 08 26 59](https://cloud.githubusercontent.com/assets/391974/17764113/970e3998-651d-11e6-8a65-6cc2b7dc3eaf.png)

**Comment by alsciende** [comment]
Oh, sorry, I misread you. You did say what happens: you get a list of all ICE. Am I right in assuming that the search field at the top contains "t:ICE d:c"?

Now, I have an idea of what can be causing this. When the "Jinteki" button is _focussed_, it sometimes looks like it's _depressed_.

Just to do a quick test, can you search for all Jinteki and Weyland ICE? What does the search field contain?

**Comment by buzard49** [comment]
It's midnight here so one last message. I had been using the back arrow of
the browser to back up a page and do another search. This is not a good
idea. What happens is the new search criteria "both,corp,runner and the
factions" seems to be added to the prior criteria. using the back arrow
does not clear out the old faction choice, even if you select a new
faction. I found 2 ways around this. Un-select ALL factions, then re-select
the one you want. This seems to clear it out. You can also hit the browser
refresh button to reload page and clear out everything.

Everything in the text boxes stays intact if you use the back arrow, All
the factions are gray as if you had not chosen one. But I think the old
faction choice is still selected, but the faction buttons color is reset,
even though your prior choice is still active. Then when select a new
faction it gets added instead of replacing prior info. So if you keep
searching just runner stuff you get weird results, then if you switch to
corp and run a search.....BONK!

Good hunting .

On Wed, Aug 17, 2016 at 11:31 PM, Cédric Bertolini <notifications@github.com

**Comment by buzard49** [comment]
In reality I just did not understand how the search engine was set up, and
did not use it correctly. Now that I know to clear search criteria out
manually before next search it will be OK. Thanks for the replys and
checking things out. This database is really a big help.
