### ISSUE TITLE
side filter `d:` doesn't work

### ISSUE THREAD

**Issue by strongoose** [Null-Signal-Games/netrunnerdb#369]
I don't know when exactly this broke but I have been unable to use the `d:runner` or `d:corp` filter for at least a week or so, possibly longer.

Steps to replicate: enter `d:runner` into the card search box on netrunnerdb; no results will be returned.

**Comment by NoahTheDuke** [comment]
Seems like it's only accepting `d:c` and `d:r`, which isn't exactly obvious. I'll look into why this is happening.

**Comment by strongoose** [comment]
huh I _think_ it used to work with the full side name, but I might be misremembering

**Comment by x3N1GM4x** [comment]
This is where only the first character of the Side code is being considered, right?

https://github.com/Alsciende/netrunnerdb/blob/0f1f43a42f898bc9a2a76638cf3aed787bd0bfa3/src/AppBundle/Service/CardsData.php#L330-L344

Specifically, lines 335 and 338 where the Side code is being `SUBSTRING`ed to only consider the first character?
