### ISSUE TITLE
Card search by faction, type or subtype is broken in other locales

### ISSUE THREAD

**Issue by dandelin** [Null-Signal-Games/netrunnerdb#37]
Meanwhile, t:ID returns identities.

Seems it's because that card database keeps identity as ID in type field.

I guess fixing the type dropdown menu in card search panel will do. (Identity -> ID)

**Comment by alsciende** [comment]
https://netrunnerdb.com/find/?q=t%3Aidentity returns the Identities, as does https://netrunnerdb.com/find/?q=t%3AIdentity

https://netrunnerdb.com/find/?q=t%3AID returns nothing

I don't understand what you're saying. Can you double-check?

**Comment by alsciende** [comment]
Maybe you are in a different locale?

**Comment by dandelin** [comment]
I checked and found that it happens only in other locale.

I browsed the site with korean locale.

https://netrunnerdb.com/find/?q=t%3AID&sort=faction&view=list&_locale=kr

and

https://netrunnerdb.com/find/?q=t%3AIdentity&sort=name&view=list&_locale=kr
