### ISSUE TITLE
OAuth and multiple accounts

### ISSUE THREAD

**Issue by Absotively** [Null-Signal-Games/netrunnerdb#377]
A user has reported that while logged into their personal account, they logged in to Always Be Running through NRDB, and found themselves logged into ABR as an organizational account they use sometimes.

**Comment by plural** [comment]
do you have more details?  An organizational account for ... what exactly?

I am starting to look into some more oauth stuff, so if there is any more detail, I'm happy to take a look.

**Comment by Absotively** [comment]
The organizational account was for NISEI. They had logged into ABR with NISEI’s account previously to set up some tournaments as NISEI.

**Comment by plural** [comment]
oh, interesting.  Thanks for the extra details.  If you want to share any other details on slack we can see if we can reproduce it and debug.

**Comment by plural** [comment]
Ok, #590 should take care of this and will be in the imminent release!
