### ISSUE TITLE
Typo: Penumbral Toolkit Flavour Text

### ISSUE THREAD

**Issue by mchippingtonderrick-afl** [Null-Signal-Games/netrunnerdb#378]
Currently reads:

> Shadow Net marketplaces have such **vulnerability** that they differ from legal platforms only in the products offered.

Should read:

> Shadow Net marketplaces have such **venerability** that they differ from legal platforms only in the products offered.

**Comment by NoahTheDuke** [comment]
thanks!

**Comment by NoahTheDuke** [comment]
Done
