### ISSUE TITLE
Feature request: legality filter

### ISSUE THREAD

**Issue by strongoose** [Null-Signal-Games/netrunnerdb#380]
Would be real handy to be able to filter cards by set legality, e.g.:
```
t:asset l:standard
```
to return all standard-legal assets

**Comment by x3N1GM4x** [comment]
Presumably you'd expect this to filter based on the most recent legal MWL?

**Comment by strongoose** [comment]
Yep! Supporting versions like

```t:asset l:standard-mwl-3.4```

would be nice too I guess, but I imagine the most common use-case is latest version of whatever the format is.

**Comment by jaimefps** [comment]
Oh man, is this feature ever going to get prioritized?
This would be super helpful to get back into deck building!
I've come back to the game after a 3 year hiatus, 
and it's really hard for me to know what are the legal cards off the top of my head.  

Happy to become a Patreon of Nisei if that'll move this feature forward.
Let me know!

**Comment by strongoose** [comment]
@jaimefps for the meantime there's a `z` filter for rotation that might help somewhat!

**Comment by plural** [comment]
i took a swing at this last week and there is a bit of a wrinkle.  The mwls and banlist info is only stored as a json blob in the database.  The card search works on SQL statements and we can't easily use a SQL query to eliminate banned cards.

We'll need to make a new table to fully filter those cards out.  One other thing we can do is add banned/rotated icons for card search results.

I'm digging in on this this week, so i'll have another update soon.
