### ISSUE TITLE
Netrunnerdb.com deck builder's 'Collection' feature including wrong cards

### ISSUE THREAD

**Issue by Boontoe** [Null-Signal-Games/netrunnerdb#39]
Since the update to the website to use a 'Collection' tab in the deck builder it's started showing some incorrect cards from sets that aren't checked.

For example, if I check every set up to and including Order and Chaos and list 'ice of influence 3' is shows the 12 correct ice that match the search but also Turing, which is from the Breaker Bay set, despite that set definitely being unchecked.  Note that the card search function outside of the deck builder page still returns correctly.

Hope this makes sense.

**Comment by erbridge** [comment]
I think this is because the two World Champion decks are always selected.
