### ISSUE TITLE
Influence sorting in Deckbuilder doesn't work correctly once Agendas are included.

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#402]
Deckbuilder allows sorting by influence:

![image](https://user-images.githubusercontent.com/10621139/72264500-c1fb3b00-3612-11ea-9917-7ce8838bfc14.png)

![image](https://user-images.githubusercontent.com/10621139/72264522-caec0c80-3612-11ea-991d-468ed6705357.png)

But, if you include Agendas as one of the card types, the order is not longer displayed correctly:

![image](https://user-images.githubusercontent.com/10621139/72264582-dfc8a000-3612-11ea-9ab2-49e3bb738278.png)

Reported by @rusefus in StimSlack.

**Comment by plural** [comment]
This is probably because the influence (helpfully called faction_cost in the DB) is NULL for agendas (and ids, FWIW).

Sorting behavior with nulls is funny.  We can probably fix this by normalizing the nulls to 0.

**Comment by plural** [comment]
the fix has been deployed to the site.
