### ISSUE TITLE
"Next page" or page numbers not showing when searching sets

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [Null-Signal-Games/netrunnerdb#408]
"Next page" or page numbers are not showing when searching sets and viewing as images, meaning you can only see the first 20(?) cards in the search.

Seen here is the top and bottom of the search for e:hap.

![Screenshot_20200120-145712_Chrome](https://user-images.githubusercontent.com/39098450/72741705-187ef100-3ba0-11ea-9f5c-d90cd4c6ddb6.jpg)

![Screenshot_20200120-145704_Chrome](https://user-images.githubusercontent.com/39098450/72741713-1c127800-3ba0-11ea-8c48-dc8ff8d2e636.jpg)

**Comment by plural** [comment]
so the cards are (apparently) sorted a bit funny during that search, but on my phone and in mobile mode in my browser, i see all 55 cards from H&P.  Would you please take another look and let me know if you see the same?

**Comment by plural** [comment]
actually, searching images mode *does* only show 20.  Huh!

**Comment by plural** [comment]
the fix has been deployed to the site.
