### ISSUE TITLE
Spaces missing in drop down menus

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [Null-Signal-Games/netrunnerdb#409]
Clicking on various drop down menus throughout the site seems to have missing spaces between words.

Seen here is the drop down for "sort by" in searches, but this also occurs on decklist screens for rotation legality.

![Screenshot_20200117-123426_Chrome](https://user-images.githubusercontent.com/39098450/72741876-71e72000-3ba0-11ea-8674-abf9cb06e38e.jpg)

**Comment by plural** [comment]
should be fixed now.
