### ISSUE TITLE
A JavaScript object is rendered in card pop-out

### ISSUE THREAD

**Issue by erbridge** [Null-Signal-Games/netrunnerdb#43]
In the pop-out for cards, `[object Object]` is displayed instead of whatever should be there, e.g.:

![screenshot from 2016-08-25 02-49-08](https://cloud.githubusercontent.com/assets/1027364/17953834/a1974516-6a6e-11e6-91ce-8c091a38ffc8.png)

**Comment by alsciende** [comment]
Fixed by 89797282a655dcbf28d0b2a61ad301f60fc4f1ad
