### ISSUE TITLE
id pictures not appearing on popular decklist or in results of decklists

### ISSUE THREAD

**Issue by j0hnofarc** [Null-Signal-Games/netrunnerdb#434]
When looking at popular decklists or searching through decklists, id avatars do not appear anymore

**Comment by plural** [comment]
Hi.  Sorry this is happening.  Would you please share what browser version and OS version you are using?

You may need to clear your cache as well, but if you share the platform info with me (and any screenshots and anything useful from the developer console) I can take a look.  The most recent release had changes to image serving, so i must have missed something.

**Comment by plural** [comment]
i haven't heard back and haven't seen this myself, so I'm going to close this out.  Please re-open if you have any more info and see it again so we can track it down.
