### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by lostgeek** [Null-Signal-Games/netrunnerdb#435]
There are Firefox Plugins like [Dark Reader](https://github.com/darkreader/darkreader) that enable you to dynamically create dark themes for any website. It does a pretty good job on NRDB (see screenshots attached), but has two main issues: Influence pips between Weyland and Neutral cards are indistinguishable. Also buttons are not easily readable in their on/off state (especially those showing how many copies of a card you include in your deck).
It would be cool to have a well-made dark mode option inbuilt to NRDB.

![image](https://user-images.githubusercontent.com/1409906/83941045-79723300-a7e8-11ea-962e-a69a9ae35f7a.png)
![image](https://user-images.githubusercontent.com/1409906/83941067-97d82e80-a7e8-11ea-853a-a6898703b1e6.png)

**Comment by tzanetl** [comment]
Dark Reader works wonderfully, except for the hover on card display

![image](https://github.com/NetrunnerDB/netrunnerdb/assets/28202976/a2431bef-a077-4144-bddc-411e6bd11776)

I tried to figure out the correct css tags to modify to fix the inversion, but for the life of me I couldn't do it. If anyone knows which tags to are responsible, [a fix could be submitted](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md) to Dark Reader.

**Comment by AlexRodwell** [comment]
Working on addressing this feature request in my draft pull-request https://github.com/NetrunnerDB/netrunnerdb/pull/788 using CSS variables. I'm using Dark Reader's dark theme as a base for the colour swaps for dark mode, although this might change before merging.

**Comment by francescopellegrini** [comment]
Thank you so much for this feature, really appreciated! 👏
