### ISSUE TITLE
Resetting password not working

### ISSUE THREAD

**Issue by 8vius** [Null-Signal-Games/netrunnerdb#439]
Everytime I log in I have to reset my password and upon resetting the password if I try to log in with it doesn't work, making me have to reset it again.

**Comment by plural** [comment]
so you are locked out right now?

are you 100% sure you are logging in with the newly reset password?  Are you copy/pasting it or is there any chance it is saved in your browser?

does this work if you try it from another browser or machine?  Does it work if you clear out your cookies?

**Comment by 8vius** [comment]
I'm not locked out, I can reset my password and log in that way I just have to reset my password every time I want to log on. And yes I am sure it just won't take for some reason, I've tried on Firefox and Chrome, reset cookies and nothing. I use a password manager so I'm certain the password is correct.

**Comment by NoahTheDuke** [comment]
What was the solution, @8vius?
