### ISSUE TITLE
Faction and Type icons reload on every deck change

### ISSUE THREAD

**Issue by Smashman** [Null-Signal-Games/netrunnerdb#443]
For some reason, every time I add or remove a card from a deck, the icons are reloaded.

Due to the icons not have a defined size without the icons being loaded, this causes a page reflow, which is very distracting.

Ideally the icons should not be reloaded this frequently, but if they have to be, they should have a defined size to stop such a reflow.

I've attached this gif below, which shows the effect:
![GIF of reflow issue](https://user-images.githubusercontent.com/2972388/90002534-aa5c6180-dc8a-11ea-92b7-b70338bc3074.gif)

Here's the frame that shows when everything is reflowed.
![Image of reflowing frame](https://user-images.githubusercontent.com/2972388/90004086-f90afb00-dc8c-11ea-8ae7-e831d084d410.png)

**Comment by plural** [comment]
thanks.  I have a fix submitted for the refresh part, but this could still
do with defined sizes, which i can get to separately.  I expect to push
this live in the next few days.

-jason
