### ISSUE TITLE
I always get Forbidden. You don't have permission to access this resource.

### ISSUE THREAD

**Issue by cmorenoserrano** [Null-Signal-Games/netrunnerdb#446]
I have imported correctly all the data from the data repository.
The next step about configuring the web server with the correct DocumentRoot I believe I have done it correctly too, but I don't know anymore.
I have given the entire netrunnerdb folder and subfolders 777 permissions and I have updated the apache httpd.conf to give all the permissions possible, but I always get the Forbidden. You don't have permission to access this resource error message.
I am so close yet so far from seeing results.
Do you know how to proceed, please?

Many thanks.
Carlos

**Comment by NoahTheDuke** [comment]
If you get on the #netrunnerdb channel of https://stimslackinvite.herokuapp.com/, you should be able to get faster answers to your questions!

**Comment by cmorenoserrano** [comment]
Thank you! I just joined.
I'll close the issue.
