### ISSUE TITLE
BanList/MWL History is duplicated on some cards 

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [Null-Signal-Games/netrunnerdb#448]
It reads:

MWL Entries
Standard Ban List 20.06 (active): Banned
Standard MWL 3.4b: Banned
Standard MWL 3.4: Banned
Standard MWL 3.3: Banned
Standard MWL 3.2: Restricted
Standard MWL 3.1: Restricted
Standard Ban List 20.06 (active): Banned
Standard MWL 3.4b: Banned
Standard MWL 3.4: Banned
Standard MWL 3.3: Banned
Standard MWL 3.2: Restricted
Standard MWL 3.1: Restricted

**Comment by rubenpieters** [comment]
For Cayambe Grid as well ( https://netrunnerdb.com/en/card/26127 ). It seems this is because the cards are present in multiple sets.

**Comment by plural** [comment]
thanks for the report. I'll take a look.
