### ISSUE TITLE
Website constantly makes me reset my password.

### ISSUE THREAD

**Issue by SSJSpeedRacer** [Null-Signal-Games/netrunnerdb#463]
I can't log into the website through the login page; every time I try, I'm told I have "invalid credentials." If I reset my password, I can log in through the password reset screen, but then when I log out/get logged out again the exact same thing happens. I've reset my password something like five times in the last two days, and no matter what, I get the same thing every time I go to log in.

EDIT: Ah shoot, nevermind, completely my fault. I was trying to log in with my email address instead of my username. Disregard.

**Comment by plural** [comment]
ah, good!  Glad you were able to get back in!  Happy deckbuilding!
