### ISSUE TITLE
Useless (?) separator on site header

### ISSUE THREAD

**Issue by francescopellegrini** [Null-Signal-Games/netrunnerdb#465]
On the left side of the login dropdown menu there is a separator pipe (see below) which was introduced in #292, but in the current layout looks like a UI bug in my opinion. Does it serve any purpose anymore?

https://github.com/NetrunnerDB/netrunnerdb/blob/6108ec616537f20abcf7fe9504f1cc55bf28aed8/app/Resources/views/layout.html.twig#L152

**Comment by plural** [comment]
i'm going to remove this as part of an upcoming set of changes that will require some navbar changes.

AFAICT, this extra LI doesn't make a difference on the page.  If you see some funky behavior / layout caused by this, please let us know with a screenshot and some browser/platform info.

Thanks!

**Comment by francescopellegrini** [comment]
Obsolete.
