### ISSUE TITLE
Uncapitalize ICE

### ISSUE THREAD

**Issue by SpencerDub** [Null-Signal-Games/netrunnerdb#466]
On card pages, the card type "ICE" is all-caps, even though both FFG and NISEI style has been to treat it as a normal noun.

"ICE" appears in all-caps in the type line on cards, but so do all other card types (both on FFG and NISEI cards), which are not presented in all-caps on card pages. "Operation", "Upgrade", "Asset", and "Agenda" are all presented in title case in card data, despite being all-caps on the card image.

I propose a simple change: ~~abolish~~ uncapitalize ICE.

**Comment by NoahTheDuke** [comment]
This is a fine change. I wonder how many places we'll have to change lol

**Comment by plural** [comment]
normal proper noun?  Ice or ice ?

**Comment by NoahTheDuke** [comment]
I wonder if anything breaks by changing the `name` here: https://github.com/NetrunnerDB/netrunner-cards-json/blob/b0b996d152f6f63196a3e8ef7218eadce4f451b7/types.json#L47

**Comment by plural** [comment]
@NoahTheDuke , is this already taken care of?

**Comment by NoahTheDuke** [comment]
It is! Good call
