### ISSUE TITLE
Normalize special characters in search

### ISSUE THREAD

**Issue by erbridge** [Null-Signal-Games/netrunnerdb#47]
Main one that comes to mind is Deja Vu, which won't autocomplete unless you type "vu", because of the accented e and a. More an annoyance than anything else, though.

**Comment by lostie** [comment]
I think rather than filter them, we could attempt to normalised them by using something like this: https://docs.oracle.com/javase/7/docs/api/java/text/Normalizer.html

What do you think @Alsciende ?

**Comment by erbridge** [comment]
Sorry, I did in fact mean to normalize them, not ignore them.
