### ISSUE TITLE
Getting locked out of accounts

### ISSUE THREAD

**Issue by gannicottb** [Null-Signal-Games/netrunnerdb#48]
I've created two accounts, both of which were created successfully. I favorited a decklist, logged out, and then received the error message 'Invalid credentials' when I tried to log back in. On the first account, I reset the password 3 or so times, to no effect. I am unable to log in with either account.

**Comment by arantius** [comment]
Every single time I log in, it tells me that my credentials are invalid.  I click forgot password (I didn't forget, you did).  I get an email, I click the link, I type /the same password/ in twice, and now I'm logged in.

I just did this one more time.  I immediately logged out and back in again: invalid credentials.

**Comment by x3N1GM4x** [comment]
Thanks for the additional report @arantius - sorry this is happening for you. Like @plural, I've been unable to reproduce this issue in the past. Perhaps you could confirm the exact browser you're using and perhaps a dump of the information in Dev Tools in your browser when you receive the Invalid Credentials message?

**Comment by x3N1GM4x** [comment]
Looks like this error comes from the core Symfony code, rather than any of our code, but I've found some suggestions online that it can be caused by having multiple users with the same username. I thought our users table had a unique index on the username field, but I'll look into this now.

Edit: Checked the prod database and we have no duplicate usernames, so guess this isn't it.

**Comment by arantius** [comment]
Firefox 70.0.1 .

Not sure what console info you want, but I see the POST to /login_check sending a 302 back to /login, which eventually fetches /info which says `{"is_authenticated":false}`....

Oh, oh my.  So in my case, I use a password manager which was automatically filling in the form.  Putting my username (and not email) in the "username" box ... actually works.  PEBKAC.  Sorry.

**Comment by x3N1GM4x** [comment]
Haha, no worries at all - gave me a chance to learn a bit more about how FOSUserBundle works. 😉 

@gannicottb - if you're still experiencing this issue, let us know and we can investigate further.
