### ISSUE TITLE
Terminal Directive Campaign currents not addable to decks

### ISSUE THREAD

**Issue by deathByLiche** [Null-Signal-Games/netrunnerdb#491]
Might be related to currents being banned, but the newly added Terminal Directive Campaign currents (Security Leak, Net Watchlist) are not able to be searched for or added to decks, even with legality set to Casual Play.

**Comment by danj3000** [comment]
Looks like these 2 are under the wrong side. (Runner Vs corp)

**Comment by plural** [comment]
i think this was fixed with https://github.com/NetrunnerDB/netrunner-cards-json/pull/568

we'll deploy the new JSON data tomorrow with the very exciting full release of System Gateway!

**Comment by plural** [comment]
fixed now.
