### ISSUE TITLE
API 2.0: deck editing history no longer present

### ISSUE THREAD

**Issue by gereons** [Null-Signal-Games/netrunnerdb#5]
The "history" property from the old API oauth2/load_deck and oauth2/decks endpoints is no longer present, is this intentional?

**Comment by alsciende** [comment]
It's not, I forgot about it. Do you use it?

**Comment by gereons** [comment]
Yes, Net Deck can parse and display this data, and allows the user to revert back to an older version.

**Comment by alsciende** [comment]
How do make sure that data is sync'ed? If your user saves a deck, returns to the menu, then reopens the deck, how do you update the History with the last edit? Do you send a request to reload the deck from NRDB?

I'm trying to figure which is better:
- to make a separate endpoint to get the history of a deck
- add the history to the "get a deck" endpoint
- add the history to the "get a deck" and the "get all decks" endpoints

**Comment by gereons** [comment]
We never worried about synchronicity in the old API (which had option 3, full history data in both endpoints). Manual syncing is possible, Net Deck has a "re-download" button for this.
We chatted about this briefly way back then, and I believe you said that when a deck gets saved from Net Deck to netrunnerdb.com, you would compute the delta between this new version and whatever was in the db. AFAIK, we've never had any complaints about this.

For the endpoints, I'd rather not make two HTTP requests to load a deck. Option 3 would be easiest for me, as it's the current implementation, but only having this info in the "get a deck" endpoint would be fine as well.

**Comment by alsciende** [comment]
Ok, so either your user is also a regular user of NRDB, and then he will need to sync both the state of the deck and its history; or the user is not a regular user of NRDB, and then he will need to sync only the history of the deck to use the "revert" feature. Correct?

Given that info, I think I will go with Option 2, which you said is fine by you. Computing the history for all the decks is too much time-consuming, knowing that most of this data won't be used at all. And a separate endpoint is useless, since you often need both data, and the state of the deck is easier to compute anyway.

**Comment by gereons** [comment]
Exactly. Thanks!

**Comment by alsciende** [comment]
Ok, it is live. The history data can be requested by adding the parameter `include_history=1`. The history data returned has a different structure from before. The timestamps are used as keys, and the variations as values.

```
{
    "version_number": "2.0",
    "data": [{
        "id": 7839,
        "date_creation": "2013-12-06T09:09:21+01:00",
        "date_update": "2016-06-07T17:23:30+02:00",
        "name": "Account Overdrawn",
        "description": "testing new cards",
        "user_id": 1,
        "user_name": "Alsciende",
        "cards": {
            "01007": 2,
            "01014": 1,
            "01017": 1,
            "01018": 3,
            "01020": 3,
            "01021": 2,
            "01022": 2,
            "01024": 3,
            "01026": 2,
            "01028": 3,
            "01050": 3,
            "01051": 2,
            "02007": 1,
            "02043": 2,
            "02087": 2,
            "02104": 3,
            "02106": 2,
            "03052": 3,
            "03054": 3,
            "04005": 2,
            "04024": 1
        },
        "history": {
            "2016-06-07T17:23:30+02:00": [
                [], {
                    "04025": 1
                }
            ]
        }
    }],
    "total": 1,
    "success": true
}
```

Now that I'm really looking at it, I can see that there is an empty Array where there should be an empty Object... Thank you PHP...

The history data shown here says that at 17:23:30 on 2016-06-07, no card was added and the card `04025` has lost `1` copy in the deck.

**Comment by alsciende** [comment]
Would you mind if I change the structure further and return one array with signed integer for each history timestamp, instead of 2 arrays, one for additions and one for removals?

**Comment by alsciende** [comment]
Sample output:

```
{
    "version_number": "2.0",
    "data": [{
        "id": 7839,
        "date_creation": "2013-12-06T09:09:21+01:00",
        "date_update": "2016-06-07T17:46:56+02:00",
        "name": "Account Overdrawn",
        "description": "testing new cards",
        "user_id": 1,
        "user_name": "Alsciende",
        "cards": {
            "01007": 2,
            "01014": 1,
            "01017": 1,
            "01018": 3,
            "01020": 3,
            "01021": 2,
            "01022": 2,
            "01024": 3,
            "01026": 2,
            "01028": 3,
            "01050": 3,
            "01051": 2,
            "02007": 1,
            "02043": 2,
            "02087": 2,
            "02104": 3,
            "02106": 2,
            "03052": 3,
            "03054": 3,
            "04005": 2,
            "04024": 1,
            "05033": 3
        },
        "history": {
            "2016-06-07T17:46:56+02:00": {
                "05033": 3,
                "01019": -3
            },
            "2016-06-07T17:36:08+02:00": {
                "01019": 3
            },
            "2016-06-07T17:23:30+02:00": {
                "04025": -1
            }
        }
    }],
    "total": 1,
    "success": true
}
```

**Comment by gereons** [comment]
Not at all, it's much nicer this way!
