### ISSUE TITLE
z:current returns Salvaged Memories cards and Gateway cards

### ISSUE THREAD

**Issue by wagnonbe** [Null-Signal-Games/netrunnerdb#501]
![Screen Shot 2021-03-29 at 1 14 37 PM](https://user-images.githubusercontent.com/1815998/112874284-bb7aa700-9090-11eb-83f2-b907115e7a9f.png)
SalMem cards are no longer legal so shouldn't show up in z:current searches alongside Gateway.

**Comment by plural** [comment]
ah, thanks for the report!  

I fixed the issue manually.

Our JSON importer doesn't handle removing cycles from a rotation.

**Comment by plural** [comment]
FYI - rotation should have taken effect on the 9th of april, so while this issue is (correctly) now fixed, z:current will return salvaged memories.  z:rotation-2021 s:fracter correctly does not now, though.
