### ISSUE TITLE
Recherche de decks / Deck Search : Side or Faction

### ISSUE THREAD

**Issue by Keizhac** [Null-Signal-Games/netrunnerdb#51]
Sorry for other who'll see this, but I'm not good enough in English to report it fully in English ^^

Salut !
Lorsque l'on choisit dans la liste des factions, il y'a parfois un bug une fois qu'on a lancé la recherche au niveau du formulaire.
Je vais tenter de te faire une liste exhaustive en mode "choisit/sélectionné après recherche".  A noter que la recherche se fait bien sur le bon critère, c'est la conservation es paramètres qui semble ne pas tout le temps fonctionner.
Les soucis rencontrés : 
Corp/Crim
Runner/any
Adam/Anarch
Apex/Anarch
Sunny Lebeau/Shaper

Si tu relances une recherche sans rien toucher dans le formulaire, ça lance bien la recherche avec la nouvelle valeur (genre Corp, relance, t'as du Crim).

Voilou !!

Et je me suis permis le français par fainéantise ^^

**Comment by alsciende** [comment]
Thanks buddy ;)
