### ISSUE TITLE
Cannot change / reset password

### ISSUE THREAD

**Issue by zacciep** [Null-Signal-Games/netrunnerdb#517]
I am currently unable to change or reset my password.  I have tried the "Forgot your password?" link numerous times with my email address and username, but never receive a password reset link by email.  I have checked my spam folder.  I have also tried on different devices (iOS phone and Windows laptop), and tried clearing cookies.  I continue to be able to log in with my old password, but would like to change it for security reasons.

I was able to successfully reset my password on thronesdb.com.

**Comment by plural** [comment]
our logs show that your server rejected these messages with an error: Sender verify failed

we use mailgun for our mail delivery and it's fine from the perspective of major email providers.
