### ISSUE TITLE
Trying to run the project: Card import step: Call to a member function getCode() on null

### ISSUE THREAD

**Issue by cloudrac3r** [Null-Signal-Games/netrunnerdb#520]
Hi, I'm trying to run the project so that I can actually test new features that I add. I'm familiar with PHP itself, but not any of the tools that surround its development like Composer and Symfony. I'm trying my best.

In the import step, when I have to run `php bin/console app:import:std -f /app/netrunner-cards-json` - the cards repository was cloned to the path `/app/netruner-cards-json` - I see this in the logs:

```
[truncated]
netrunnerdb_1  | Importing Cards...
netrunnerdb_1  | Changing the code of  
netrunnerdb_1  | Changing the deckLimit of 11001 
netrunnerdb_1  | Changing the position of 11001 
netrunnerdb_1  | Changing the quantity of 11001 
netrunnerdb_1  | Changing the strippedTitle of 11001 
netrunnerdb_1  | Changing the title of 11001 
netrunnerdb_1  | Changing the uniqueness of 11001 System Outage
netrunnerdb_1  | Changing the illustrator of 11001 System Outage
netrunnerdb_1  | Changing the keywords of 11001 System Outage
netrunnerdb_1  | Changing the text of 11001 System Outage
netrunnerdb_1  | Changing the strippedText of 11001 System Outage
netrunnerdb_1  | Changing the cost of 11001 System Outage
netrunnerdb_1  | 
netrunnerdb_1  | In ImportStdCommand.php line 510:
netrunnerdb_1  |                                                
netrunnerdb_1  |   Call to a member function getCode() on null  
netrunnerdb_1  |                                                
netrunnerdb_1  | 
netrunnerdb_1  | app:import:std [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <path>
```

When I try to use the web interface, none of the cards exist, which aligns with my assumption that the cards weren't imported correctly.

What can I do about this?

**Comment by plural** [comment]
hey there!  Sorry you ran into trouble.

It looks like a fix to quiet down noisy messages on subsequent updates broke things for you here.

on 510, take out "&& ($entity->getType()->getCode() == 'identity' || $entity->getType()->getCode() == 'agenda')" and give it another whirl.

https://github.com/NetrunnerDB/netrunnerdb/commit/6495d209fd4c7c1808db0110cd8faec2c9e1d859 is the original patch that added this - if you unwind that locallly you should be fine.  

I'll try to get to a patch for the empty environment case this weekend.

**Comment by cloudrac3r** [comment]
That was the cause. `git revert` on that commit allowed the database to load correctly. (I also `git pull`ed the last 5 days of commits.)

**Comment by plural** [comment]
i think this has been fixed for a while.
