### ISSUE TITLE
Switching format to Casual fails

### ISSUE THREAD

**Issue by Treiral** [Null-Signal-Games/netrunnerdb#54]
Whenever I have a deck saved for MWL 1.1, and then Edit, switch to Casual, and Save. It goes back to the "My decks" page correctly. But when I check the deck, it's still in MWL.
If I duplicate the deck, it correctly appears as Casual.
I tried clearing the cache (I use Clear Cache Chrome extension for that) but to no avail.

**Comment by plural** [comment]
i tested this out a few times with several different MWL versions and couldn't reproduce.

Please re-open if you see this recurring.
