### ISSUE TITLE
"Gold Farmer" is not searchable during Deckbuilding, even with "all" packs selected.

### ISSUE THREAD

**Issue by CryptoGraham278** [Null-Signal-Games/netrunnerdb#545]
Cannot find gold farmer using the deckbuilding tool, regardless of format selected.

The only other NBN ice from Uprising, F2P, is easily found and searchable. 

Gold Farmer still has an NRDB card entry, however and can be accessed.

**Comment by plural** [comment]
this is working as intended. Gold Farmer is banned in the last 3 banlists and we hide banned cards based on the ban list selected in the deckbuilder.  If i select a ban list of 20.06 or earlier, Gold Farmer shows up as expected.
