### ISSUE TITLE
Card Wording Updates

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [Null-Signal-Games/netrunnerdb#551]
Glut Cipher is supposed to have the Corp trash the cards from HQ at random. It should say: "If they do, they trash..."

"We did not intend to include new text for Hivemind in this update." Hivemind will need its old text (whatever that was).

Link to the Twitter thread these come from: https://mobile.twitter.com/NISEI_Rules/status/1424571358172770308?s=20

**Comment by francescopellegrini** [comment]
This probably belongs to [the card data repo](https://github.com/NetrunnerDB/netrunner-cards-json).

**Comment by plural** [comment]
i have a PR open for glut cipher and am going to make one for hivemind as well.  Gonna close this one out here since it isn't the right repo for the issue, but thanks for the report!
