### ISSUE TITLE
Feature Request: mini faction quick filter

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [Null-Signal-Games/netrunnerdb#553]
Is there a way we could get "AD"/"AP"/"SL" added as filters for the three mini factions?

**Comment by plural** [comment]
oh, huh.

We don't have the faction "short codes" documented on the public pages.

f:adam f:apex and f:sunny-lebeau all work, but that isn't documented anywhere.

ad / ap / sl are good abbreviations.

i'll get that patched up and update the syntax pages with some info on this as well.
