### ISSUE TITLE
Relative Links in Rulings Behave Inconsistently

### ISSUE THREAD

**Issue by infinitenutshell** [Null-Signal-Games/netrunnerdb#557]
Repro Steps:
1. Add a ruling to any System Gateway card with text that includes a link to the same or another card, using `[cardname](#####)` (or `[cardname](en/card/#####)`, without a leading `/`)
2. Note that on the page for the card where you added the ruling, mousing over or clicking on the link shows the popup or goes to the page corresponding to the card number used.
3. Find the ruling in this search: https://netrunnerdb.com/en/set/sg/rulings
4. Observe that on this page, the mouseover popup still works correctly, but the actual URL the link directs to is wrong

Expected Behavior: Cards can be hyperlinked by their 5-digit card number, and the links will go to that card's page in any search results page that shows the ruling in question
Actual behavior: In search results, hyperlinks given as relative paths add garbage (taken from the search parameters?) into the URL, breaking the links, even though the mouseover popup still finds the card information correctly.

Comments:
I haven't tested how widespread this is. We ran into it when reviewing the page of all SG rulings linked in step 3 above (the Rules Team is going to tweet that link in our announcement that SG card Q&A is now online). I'd be surprised if it's specific to System Gateway or that particular search.

As a workaround, we updated all the links in SG card rulings to use absolute paths, i.e. `[cardname](/en/card/#####)`. I'm not sure what is actually supported syntax—maybe we were supposed to use absolute paths all along? But the fact that mouseover popups still work suggests to me that there's an actual bug in expected functionality here.

**Comment by plural** [comment]
so this isn't actually behaving inconsistently.  [text](####) creates a relative link to ##### .
![Screenshot 2022-02-07 11 49 15 PM](https://user-images.githubusercontent.com/396562/152926366-a2cc41e3-b57a-48c7-b427-24182d682ca1.png)

The ruling text box supports the same autocomplete that the decklist descriptions do, so you can insert cards by typing a '#' and then typing a card name, like so:
![Screenshot 2022-02-08 12 00 17 AM](https://user-images.githubusercontent.com/396562/152927549-ba453245-8c18-434f-b934-2ca8763767f0.png)

If you do this, it will use a proper root-relative link and should take care of this issue for you.

Please re-open or reach out if you need some more help wtih this.
