### ISSUE TITLE
Internal Server Error 500 on save attempt & save copy attempt

### ISSUE THREAD

**Issue by sb-so** [Null-Signal-Games/netrunnerdb#558]
Hi,
I reproduced an internal server error several times with a corp deck, when clicking on save or save copy.
The deck is this one: https://netrunnerdb.com/en/deck/edit/1424829. Card list:
The Shadow Pulling the Strings
135 influence spent (max ∞, available Infinity)
44 agenda points (between 44 and 45)
107 cards (min 30)
Cards up to All That Remains
Agenda Agenda (27)
1x Accelerated Beta Test
1x AstroScript Pilot Program
1x Bifrost Array
1x Braintrust
1x Breaking News
1x Character Assassination
1x Corporate War
1x Director Haas' Pet Project
1x Efficiency Committee
1x Executive Retreat
1x False Lead
1x Geothermal Fracking
1x Gila Hands Arcology
1x Hostile Takeover
1x License Acquisition
1x Mandatory Upgrades
1x Nisei MK II
1x Posted Bounty
1x Priority Requisition
1x Private Security Force
1x Profiteering
1x Project Ares
1x Project Atlas
1x Sentinel Defense Program
1x Superior Cyberwalls
1x TGTBT
1x Vulcan Coverup
Asset Asset (20)
1x Adonis Campaign ●●
1x Alix T4LB07 ●
1x Broadcast Square ●●●
1x Cerebral Overwriter ●●
1x Daily Business Show ●
1x Dedicated Response Team ●●●
1x Edge of World ●●
1x Encryption Protocol ●
1x Executive Boot Camp ●
1x Ghost Branch ●
1x GRNDL Refinery ●●
1x Haas Arcology AI ●●●●
1x Marked Accounts ●
1x Project Junebug ●
1x Reversed Accounts ●
1x Ronin ●●●●
1x Security Subcontract ●
1x Shock! ●●
1x Snare! ●●
1x Sundew ●●●
Operation Operation (24)
2x Beanstalk Royalties ●●
1x Biotic Labor ●●●●
1x Blue Level Clearance ●●
1x Celebrity Gift ●●●
1x Closed Accounts ●
1x Corporate Shuffle ●●
1x Green Level Clearance ●
2x Hedge Fund
1x Neural EMP ●●
1x Peak Efficiency ●
1x Power Shutdown ●●
1x Precognition ●●●
1x Punitive Counterstrike ●●
1x Restructure
1x Reuse ●
1x Scorched Earth ●●●●
1x SEA Source ●●
1x Shipment from MirrorMorph ●●
1x Shipment from SanSan ●
1x Successful Demonstration ●
1x Sweeps Week ●●
1x Trick of Light ●●●
Upgrade Upgrade (9)
1x Amazon Industrial Zone ●
1x Ash 2X3ZB9CY ●●
1x Corporate Troubleshooter ●
1x Crisium Grid ●
1x Experiential Data ●
1x Panic Button ●
1x Red Herrings ●●
1x Research Station ●
1x Strongbox ●●
Barrier Barrier (9)
1x Changeling ●●
1x Eli 1.0 ●
1x Heimdall 1.0 ●●
1x Himitsu-Bako ●●
1x Hive ●●
1x Ice Wall ●
1x TMI ●
1x Tyrant ●●
1x Wraparound ●
Code Gate Code Gate (9)
1x Bullfrog ●●
1x Cell Portal ●●
1x Hourglass ●●
1x Hudson 1.0 ●
1x NEXT Bronze ●●
1x Pop-up Window ●
1x Viktor 1.0 ●●
1x Viktor 2.0 ●●●
1x Wendigo ●●
Sentry Sentry (9)
1x Data Hound ●
1x Lancelot
1x Rototurret ●
1x Shadow ●
1x Sherlock 1.0 ●●
1x Snoop ●●
1x Swordsman ●
1x Uroboros ●●
1x Woodcutter ●●●

A similar sized deck on runner side worked fine. The error with this deck persisted sdveral changes, independent of legality status of the deck (e.g. agenda pts)

Error:
![Screenshot_20211012-223910](https://user-images.githubusercontent.com/92445582/137141030-bf0a42fc-02c1-40c9-a3cb-b14191badc00.png)

**Comment by plural** [comment]
i imported this deck to our dev environment and I can't reproduce this.

If you encounter this again, please reach out to us on #netrunnerdb on stimslack or #jnet-nrdb-cobra on GLC so we can try to look at things while you are encountering the issue.
