### ISSUE TITLE
"Compare decks" function seems to not work at all

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [Null-Signal-Games/netrunnerdb#565]
In the my decks window the "with selection" dropdown opens but neither of the compare buttons seem to do anything.

**Comment by plural** [comment]
do you have 2 or more decks selected already?

shift-click the decks before selecting the decks.

Are you trying this on mobile?  it doesn't seem to work on mobile because there isn't a shift-click option.  :(

**Comment by Tamijo-Netrunner** [comment]
Ah. In that case is there any chance we could have a "select deck" button explicitly somewhere? It does not seem intuitive as it stands. I believe I was trying it on desktop.

**Comment by plural** [comment]
Yeah, checkboxes or something would be better.  I can easily add a bit of
help text quickly, at least.
