### ISSUE TITLE
Can I input the cards I own to build new decks from?

### ISSUE THREAD

**Issue by scotluman** [Null-Signal-Games/netrunnerdb#566]
Hello, 

Thanks for this great resource. I am new to deck building and new to Netrunner so I am excited to play around on here to build decks. I was wondering if under my profile I am able to check/uncheck the sets I have so that when building decks, the selections would utilize that information to narrow down my choices. Is that a feature and if so, could I get a little direction on using it?

Thanks a ton, for your coming answer, and again for the work you've done as a whole!

**Comment by plural** [comment]
hello!

Thanks for the kind words.  :)

Yes, you can set the cards you own.  On the deckbuilder page, the "Collection" button will list all the packs that have been published.  

![Screenshot 2021-11-14 5 01 28 PM](https://user-images.githubusercontent.com/396562/141702216-2c720528-147c-49b6-93a3-83898c31209f.png)

On the decklist search page you can also set the packs you have and can filter searches to decks with only cards in those packs as well.
![Screenshot 2021-11-14 5 03 26 PM](https://user-images.githubusercontent.com/396562/141702255-18495d86-1357-481f-8883-f035a84f7120.png)

![Screenshot 2021-11-14 5 03 32 PM](https://user-images.githubusercontent.com/396562/141702258-3dd9e372-3904-4cdb-9956-3a68f2ab2787.png)

**Comment by scotluman** [comment]
Thanks for getting back to me. I was able to find the settings for the deck search but haven't found them for the deck builder yet. When I go to build a runner deck it brings me here https://netrunnerdb.com/en/deck/new/runner 

Do I have to start with an identity before the filtering options become visible?

Thanks again!

**Comment by plural** [comment]
ah, yes! you do have to select an id first, then you will get the view i screenshotted.  The settings aren't sticky across the site - they are local to the deckbuilder.

**Comment by plural** [comment]
I don't think we have any TODOs from this issue, so I'm gonna close it out.

Please reach out if you still have issues.
