### ISSUE TITLE
Clicking on a deck in My Decks page scrolls it to the top

### ISSUE THREAD

**Issue by francescopellegrini** [Null-Signal-Games/netrunnerdb#581]
Could it be that #577 forgot to add `event.stopPropagation();` to this function?

https://github.com/NetrunnerDB/netrunnerdb/blob/cc5b132d6c325a3b7441c7353df514cb7b4f776d/web/js/decks.v2.js#L45-L48

**Comment by distributive** [comment]
That's my bad for not testing with enough decks in my test account. Thanks for raising this!
