### ISSUE TITLE
Urls of some decks have no uuid

### ISSUE THREAD

**Issue by francescopellegrini** [Null-Signal-Games/netrunnerdb#584]
I noticed this bug clicking on Matuszczak's decks from the "Last 10 decklists": their url miss the uuid value, es `https://netrunnerdb.com/en/decklist//pd-rush`

It seems to date [back to January 27th](https://netrunnerdb.com/en/decklists/find?faction=&sort=date&rotation_id=&author=Matuszczak&title=&is_legal=&mwl_code=&packs%5B%5D=su21&packs%5B%5D=sg&packs%5B%5D=sm&packs%5B%5D=mor&cycle_21=ashes&packs%5B%5D=ur&packs%5B%5D=urbp&packs%5B%5D=df&packs%5B%5D=sc19&packs%5B%5D=napd&packs%5B%5D=mo&packs%5B%5D=rar&cycle_16=kitara&packs%5B%5D=ka&packs%5B%5D=win&packs%5B%5D=tdatd&packs%5B%5D=cotc&packs%5B%5D=dtwn&packs%5B%5D=ss&packs%5B%5D=core2&cycle_14=terminal-directive&packs%5B%5D=tdc&packs%5B%5D=td&cycle_13=red-sand&packs%5B%5D=cd&packs%5B%5D=fm&packs%5B%5D=baw&packs%5B%5D=eas&packs%5B%5D=so&packs%5B%5D=dc&cycle_12=flashpoint&packs%5B%5D=qu&packs%5B%5D=ml&packs%5B%5D=in&packs%5B%5D=es&packs%5B%5D=bm&packs%5B%5D=23s&cycle_11=mumbad&packs%5B%5D=ftm&packs%5B%5D=tlm&packs%5B%5D=si&packs%5B%5D=dag&packs%5B%5D=bf&packs%5B%5D=kg&packs%5B%5D=dad&cycle_9=sansan&packs%5B%5D=uot&packs%5B%5D=oh&packs%5B%5D=uw&packs%5B%5D=cc&packs%5B%5D=bb&packs%5B%5D=val&packs%5B%5D=oac&cycle_7=lunar&packs%5B%5D=ts&packs%5B%5D=atr&packs%5B%5D=uao&packs%5B%5D=fc&packs%5B%5D=tsb&packs%5B%5D=up&packs%5B%5D=hap&cycle_4=spin&packs%5B%5D=dt&packs%5B%5D=fal&packs%5B%5D=tc&packs%5B%5D=mt&packs%5B%5D=st&packs%5B%5D=om&packs%5B%5D=cac&cycle_2=genesis&packs%5B%5D=fp&packs%5B%5D=hs&packs%5B%5D=asis&packs%5B%5D=ce&packs%5B%5D=ta&packs%5B%5D=wla&packs%5B%5D=core) at least.

**Comment by plural** [comment]
Thanks for the report!

All of those decks came in via ABR which helped me track it down.  I'll get things sorted today.

Only 23 decks have this issue right now, but I know where the issue is.
