### ISSUE TITLE
Jinteki Logo in Card Ability for Raman Rai Fails to Render.

### ISSUE THREAD

**Issue by SyxP** [Null-Signal-Games/netrunnerdb#595]
For https://netrunnerdb.com/en/card/10068 (Raman Rai), 
> This card costs 0 influence if you have 6 or more non-alliance {jinteki} cards in your deck. (...)

This is in contrast to say Heritage Committee, which does render correctly.

**Comment by francescopellegrini** [comment]
This belongs to the [cards repo](https://github.com/NetrunnerDB/netrunner-cards-json) and it's apparently [already been fixed](https://github.com/NetrunnerDB/netrunner-cards-json/commit/8075d7efdbec71f55f9a0608a4d5cf11e0268008).

**Comment by SyxP** [comment]
Ah I was looking through Heritage Committee and Raman Rai and comparing the two, but fail to notice that they use different braces, hence I assume it might be a non-card related issue.
