### ISSUE TITLE
Trying to logout results in a 500 internal server error

### ISSUE THREAD

**Issue by kjchiu** [Null-Signal-Games/netrunnerdb#613]

**Comment by plural** [comment]
Do you have any other info? What username perhaps?

Does this happen in an incognito window, with a separate account?

**Comment by kjchiu** [comment]
Tried on multiple accounts (secretfisk, sadstug)
Multiple browsers (Firefox 98.0.1, Chrome 99.0.4844.82)
With/without incognito

**Comment by plural** [comment]
Thanks.  I was able to reproduce and grab a trace.

Sorry for the hassle, but thanks for the report!
