### ISSUE TITLE
Potential Unleashed

### ISSUE THREAD

**Issue by Dissinger** [Null-Signal-Games/netrunnerdb#62]
I'm having issues with starting a deck using potential unleashed. Everytime I do this is what I see...
![potential unleashed bug](https://cloud.githubusercontent.com/assets/17139532/19362727/cb5dfa44-9155-11e6-800b-bc229a04e2d5.png)

**Comment by alsciende** [comment]
Other IDs are fine? What about Haas-Bioroid: Architects of Tomorrow?

**Comment by Dissinger** [comment]
Seems every ID does this, works fine on the mobile site, but on my laptop I can't get anything to come up...I am on Chrome for windows 10 and have webroot installed.

**Comment by alsciende** [comment]
What if you disable webroot for a session?

**Comment by Dissinger** [comment]
I am having trouble disabling it. I have uninstalled and reinstalled chrome. Looks like that took care of it. Webroot was expiring in two days anyways, was weird because it only just started doing this.
