### ISSUE TITLE
1111 validation never allows 3 Desperados

### ISSUE THREAD

**Issue by zaroth** [Null-Signal-Games/netrunnerdb#63]
3 Desperados and other similar core set multiples should be available and valid in the format as long as no other +1 card is selected.

**Comment by alsciende** [comment]
Could not reproduce. Created a deck with Andromeda and 3x Desperado. The deck is 1.1.1.1 compliant.

**Comment by zaroth** [comment]
Alright, I must admit I didn't check this myself, just forwarded a report from a local player. If I find a concrete example, I'll get back here.

**Comment by zaroth** [comment]
The original reporter checked again and admitted that he got confused by another card (Bank Job) not having 3 copies in the core set. Sorry for the confusion, everything works great!
