### ISSUE TITLE
Transfer analytics

### ISSUE THREAD

**Issue by plural** [Null-Signal-Games/netrunnerdb#638]
Hey Noah, please reach out to plural with your email that owns nrdb analytics so we can transfer it into the new analytics account.

**Comment by NoahTheDuke** [comment]
Ah shit you asked me for this like two months ago 💀

**Comment by NoahTheDuke** [comment]
Yes i can absolutely do that for you.

**Comment by plural** [comment]
Hehehehe. You have a new little one! No worries.

**Comment by plural** [comment]
oh, i guessed and upgraded the one you had as a reader for nisei to admin so if i guessed correctly, you should be able to move the NRDB property over.  https://support.google.com/analytics/answer/6370521

**Comment by NoahTheDuke** [comment]
I think it was successful? I followed the instructions, so just let me know if there's more that I need to do.

**Comment by plural** [comment]
Looks like it! I see it in the project nisei view. Thanks!
