### ISSUE TITLE
"Sort by set" displaying cards out of order.

### ISSUE THREAD

**Issue by Wheels2050** [Null-Signal-Games/netrunnerdb#65]
Using the sort by set function on the following decklist puts Quandary and Yagura out of order (Quandary is mistakenly shown first):

https://netrunnerdb.com/en/decklist/38388/bloom-nobly-ink-black-cherry-blossoms#

**Comment by whiterabbit1670** [comment]
Can confirm sort issue with Fear & Loathing and Double Time in wrong order:

https://netrunnerdb.com/en/decklist/41358/anr-corp-cube-draft-cards-up-to-quorum

https://goo.gl/photos/R13CuKunkbbiBCPs5

**Comment by NoahTheDuke** [comment]
Thanks for the reports, y'all. It's been fixed!
