### ISSUE TITLE
[Bug] Card Suggestions disappearing

### ISSUE THREAD

**Issue by Deckbauer** [Null-Signal-Games/netrunnerdb#66]
When i open a Deck and the site is building up, i can see the tab "Card suggestions" above "name" and "legality" in the left column. Shortly before site finished loading the tab disappears. I see it exactly until before the site displays all images and is finished rendering.

Running Ubuntu 16.04 (64 bit), with Firefox 49.0. Same behavior with Cromium 53.0.2785.143

**Comment by u86** [comment]
I'm having the same issue with Windows 10 and Chrome 53.0.2785.143 m.
