### ISSUE TITLE
NRDB seach engine thinks [[The Source]] has 0 influence

### ISSUE THREAD

**Issue by EnsuVerna** [Null-Signal-Games/netrunnerdb#664]
[[The Source]] does not show up on NRDB when you search for neutral runner cards that cost 2 influence.

https://netrunnerdb.com/find/?q=f%3Anr+n%3A2&sort=name&view=list&_locale=en

I tried playing with the search results to see what it _thinks_ it is, and it appears to show up in 0 influence searches.

https://netrunnerdb.com/find/?q=source+n%3A0&sort=name&view=list&_locale=en

https://cdn.discordapp.com/attachments/425105101451952130/997624318932549822/unknown.png

It shows 2 inf in the results bar, and Sahasrara works correctly in GLC.  Not sure where the bug is exactly.

**Comment by plural** [comment]
de-duping against #692
