### ISSUE TITLE
search for influence value missing some results

### ISSUE THREAD

**Issue by insanit** [Null-Signal-Games/netrunnerdb#667]
searched for n:5, noticed that Assimilator and Logic Bomb did not appear, did not do any testing to see where they might pop up

**Comment by yojimbosteel** [comment]
I can verify that something is wrong. I tried to search for influence under 2 and got incorrect results.

Example searches:

n<2 f:apex
https://netrunnerdb.com/find/?q=n%3C2+f%3Aapex&sort=name&view=list&_locale=en
Returns:~ Apex: Invasive Predator, Assimilator, Harbinger, Hunting Grounds, and Wasteland

n:2 f:apex
https://netrunnerdb.com/find/?q=n%3A2+f%3Aapex&sort=name&view=list&_locale=en
Returns:~ Endless Hunger and Prey

n>2 f:apex
https://netrunnerdb.com/find/?q=n%3E2+f%3Aapex&sort=name&view=list&_locale=en
Returns:~ Apocalypse, Consume, Heartbeat, Reaver, and Reboot

**Comment by plural** [comment]
de-duping against #692
