### ISSUE TITLE
Feature Request: Links/Tabs to move between card lists of each data pack

### ISSUE THREAD

**Issue by Riley5** [Null-Signal-Games/netrunnerdb#67]
Poor mockup: http://i.imgur.com/ylLb8sE.jpg

Currently viewing the card list for Blood Money, 2nd pack in the current cycle. Left tab will take you back to the card list for 23 Seconds, the first pack, while right tab will bring you to Escalation, the third. Would be a nice convenient change, though hopping between cycles/deluxes might be weird.

**Comment by NoahTheDuke** [comment]
That imgur link doesn’t show what I think you mean it to show
