### ISSUE TITLE
Currents returned as search result for Standard August 2022

### ISSUE THREAD

**Issue by allesginevra** [Null-Signal-Games/netrunnerdb#679]
When I use the following search - d:c b:standard-ban-list-22-08 z:rotation-2022 - a number of currents are returned in the search results but all currents are on the standard ban list

**Comment by plural** [comment]
We had an issue a while back with the banlist filter behaving opposite to how we wanted it to (and how people expect it to).

I can't reproduce this issue now, so i assume that was the cause.  Please re-open if you see it any more.
