### ISSUE TITLE
Searching for 0 influence cards gives a bunch of wrong results

### ISSUE THREAD

**Issue by 11-41-41** [Null-Signal-Games/netrunnerdb#684]
Searching for z:current f:shaper|criminal n:1 doesn't return Aeneas, which it should. Searching for z:current f:shaper|criminal n:0 reveals that many cards have the wrong influce atrributed to them in regards to search syntax. The influence pips shown in the results are still correct.

**Comment by plural** [comment]
moved to the proper repository.

**Comment by plural** [comment]
de-duping against #692
