### ISSUE TITLE
ssl redirect doesn't work for all routes

### ISSUE THREAD

**Issue by kjchiu** [Null-Signal-Games/netrunnerdb#691]
eg. http://www.netrunnerdb.com/en/decklist/54bf6c7c-7095-4e3d-b183-3293fc0846d8/controlling-the-bladder
doesn't redirect to https://www.netrunnerdb.com/en/decklist/54bf6c7c-7095-4e3d-b183-3293fc0846d8/controlling-the-bladder

**Comment by plural** [comment]
huh.  Thanks for the report!

**Comment by plural** [comment]
ah, thanks!  our config didn't handle www.netrunnerdb.com!  Thanks a ton for this report.  I've patched this up.
