### ISSUE TITLE
Influence Search is behaving incorrectly

### ISSUE THREAD

**Issue by plural** [Null-Signal-Games/netrunnerdb#692]
New umbrella issue for influence search shenanigans.

Other issues will be de-duped against this one.

**Comment by plural** [comment]
the three duplicated bugs have several good examples of this not behaving properly.

**Comment by muyjohno** [comment]
+1. As an example, look at this list of "0-inf" shaper cards: https://netrunnerdb.com/find/?q=f%3Ashaper+n%3A0&sort=name&view=list&_locale=en

Looks like lots of cards are erroneously considered to have 0 inf; they seem to be the ones excluded from other searches.

**Comment by muyjohno** [comment]
Apologies for the double-post but I think I have an idea after doing a little more testing.

It seems like all of the cards that are incorrectly matching on influence are resources. This switch case (https://github.com/NetrunnerDB/netrunnerdb/blob/main/src/AppBundle/Service/CardsData.php#L564) handles influence filtering and appears to handle two different logical cases depending on whether the type's ID is 9. I'm guessing from the implementation that it expects ID 9 to be identities (in which case it will filter on influence limit instead). I think that what's happened instead is that ID 9 in the production environment is actually resources, and that those are filtering against their influence limit (which does not exist) and falling back to 0.

Identities are also appearing as 0 influence and searching for, e.g. 15 influence returns no results, possibly confirming this theory.

This json data (https://github.com/NetrunnerDB/netrunner-cards-json/blob/main/types.json) has identity as the 9th type, which might mean that in a fresh environment it has ID 9, so it may pass testing.

**Comment by plural** [comment]
gahahahahahahahahahahsdfiuyhsdiufhasdiouhfasidufhaerble

Oh, this is so my fault.  Thanks for bailing this out, Johno!
