### ISSUE TITLE
Banlist search is in bizarro mode

### ISSUE THREAD

**Issue by plural** [Null-Signal-Games/netrunnerdb#699]
From a glc report: Hey folks, nrdb search with "b:active" returns all the cards that are *banned* rather than legal in the new sbl. Is this a known issue? (the workaround is typing b!active)

**Comment by PreNic** [comment]
I can confirm that. If you try "z:current x:power" you get 45 cards. "z:current x:power b:active" returns only 2 cards that are the banned ones.

**Comment by distributive** [comment]
I believe the issue here is that the banlist query is getting banned cards when it should be getting non-banned cards, in which case this has been resolved by #707
