### ISSUE TITLE
Pre-Load/Cache Illustrators Page

### ISSUE THREAD

**Issue by GordonsBeard** [Null-Signal-Games/netrunnerdb#700]
Currently the "Illustrators" page takes a few seconds to actually load and compile. I cannot imagine this page updates daily/weekly at all so I propose it would be better to create some kind of offline process to generate this page instead of trying to calculate it all on page load, online.

I could be wrong and this isn't really a "bug" more of a suggestion to reduce some load the website might experience given this page's length to load.

**Comment by plural** [comment]
yeah it's looking slow.  :). We're doing some more work on the new API to improve performance so we'll keep an eye on this.

**Comment by plural** [comment]
the fixes for this have been deployed.  Sorry for downloading ... checks notes ... 9.5MB before.  Down to 125KB.

Thanks for letting us know!
