### ISSUE TITLE
Spamming/phishing on decklist comments

### ISSUE THREAD

**Issue by AxW1ll** [Null-Signal-Games/netrunnerdb#709]
Don't know if this is the right place, but I couldn't find another channel I had access to.

The decklist I posted yesterday got almost right away two identical comments that seem like they are fishing attempts. (Either bot captured the account or an account completely created for that purpose, can't really tell.) Hid them from the general public, but felt a need to report this further.

Decklist in question:
https://netrunnerdb.com/en/decklist/5298c6a4-d9d6-4f6f-88a3-80e269367d98/my-other-car-is-porsche-my-other-deck-was-snacs-20th-at-wo

**Comment by plural** [comment]
this was resolved.
