### ISSUE TITLE
What is my "NRDB Deck ID"?

### ISSUE THREAD

**Issue by saccenti** [Null-Signal-Games/netrunnerdb#717]
Looking to import deck from NRDB using Jinteki.net "Import Deck" button (rather than, say, a copy/paste text method).

It asks for "NRDB Deck ID". How do I discern what this ID might be, when viewing my deck on NRDB?

Intuitively, I would think to find it in the string from the URL.

For instance, when viewing a deck of mine at this address: https://netrunnerdb.com/en/deck/view/7e591fe9-5863-425e-897b-14afc4659103

I would think the DeckID would be the "7e591fe9-5863-425e-897b-14afc4659103" portion. 

But this yields no joy, so I'm not seeing something obvious.

**Comment by plural** [comment]
you should be able to paste the full url for your deck into jnet.

If your settings don't allow the decks to be viewed, that won't work.

-jason
