### ISSUE TITLE
Incorrect IDs offered in Start-up deck building

### ISSUE THREAD

**Issue by tdkenny** [Null-Signal-Games/netrunnerdb#721]
When building a deck rotated out ID are still included in the Start-up list and the New Neutral ID (Ampère and Nova) are not on the list 
Screenshot from Runner deck-building as an example.
![Screenshot 2022-12-13 at 10 02 28](https://user-images.githubusercontent.com/70032542/207289345-6195cad8-cd6d-4fb9-be12-f46674855046.jpg)

**Comment by plural** [comment]
I'm not able to reproduce this. 

<img width="1119" alt="Screenshot 2022-12-15 at 11 36 50 PM" src="https://user-images.githubusercontent.com/396562/208029792-e37015ca-21df-4f47-b7ae-0978cb0163bb.png">
