### ISSUE TITLE
Feature request: Display deck modification after editing a deck

### ISSUE THREAD

**Issue by XavierSamuelHuppe** [Null-Signal-Games/netrunnerdb#74]
It would be great if, after having made some modifications to a deck online in the "My decks" section, we saw a list of all modifications done. This would help to after redo those modification to a physic deck.

Exemple:
-----------
Changes so far:
+1 Faust
+1 Amped Up
-1 Eater
-1 Wanton Destruction
-----------

This automatically while doing modifications to the deck or after hitting save. With green and red color for +s and -s respectively.

**Comment by alsciende** [comment]
Isn't that what the "History" tab is for?

**Comment by XavierSamuelHuppe** [comment]
This is my bad. I didn't see. How to close this thing..?
