### ISSUE TITLE
Feature request: hashed deck ids

### ISSUE THREAD

**Issue by cyberewok** [Null-Signal-Games/netrunnerdb#75]
Currently when I create new private decks in a short space of time the url in the view section has deck IDs that are within 1 or 2 of the previous. It surprised me that this was possibly not a hashed number but a counter (please correct me if I'm missing something). This is potentially open to abuse as private decks of users that have 'share private decks' on can all be scraped by url and matched to user (the username is on the view page of private decks). This means if a user wants to share any private decks they are at risk of making all their private decklists being essentially public. One solution (which is obviously not backwards compatible) is for future decklists to create a much longer random id and use that in the view url. This essentially stops the ability to scrape the urls.

It is tempting to assume noone would bother scraping the urls so this may not be a priority issue. Also my background is not security and I obviously haven't tried any scraping of urls so I also apologise if you have another measure already in place to stop this (such as max requests server side or something).

**Comment by plural** [comment]
you can make a good argument that this is either an enhancement request or a bug.  :)

**Comment by plural** [comment]
This has been handled with the updates to use UUIDs for deck and decklist IDs.
