### ISSUE TITLE
Eternal Points List Outdated

### ISSUE THREAD

**Issue by AugustusCeasar** [Null-Signal-Games/netrunnerdb#758]
The [list of format banlists](https://netrunnerdb.com/en/banlists) is missing the latest [Eternal Points list update](https://nullsignal.games/players/supported-formats/#eternal) from the 23th March 2023.

Notably, Ob is one more point than listed. Tech Traders is 1 less. And some other minor changes of points.

**Comment by plural** [comment]
This should be fixed now.
