### ISSUE TITLE
Feature request: Add image upload functionality

### ISSUE THREAD

**Issue by lostgeek** [Null-Signal-Games/netrunnerdb#768]
It's always a pain to upload your memes for write-ups somewhere and external links are prone to getting taken down.
Would be great if you could drag&drop images into the Notes field and have it auto-upload similar to how github does it.

**Comment by plural** [comment]
We are unlikely to add image upload support.  Our moderation is already pretty light and we certainly don't want to host random images uploaded by people, especially when those "people" can sometimes be scammers and cryptospammers and the like.
