### ISSUE TITLE
Allow chosing different version of identity

### ISSUE THREAD

**Issue by morvael** [Null-Signal-Games/netrunnerdb#769]
The system forces me to pick newest version of given identity card and there's no option to change it afterwards. This makes using the right card in deck impossible.

**Comment by plural** [comment]
we won't be fixing this in current NRDB but you will be able to do this in the new version eventually.

I assume by "the right card" you mean "an earlier printing of the card i already have in my collection".  While this is admittedly a bit annoying, it isn't incorrect.  Any printing of a legal card is legal and using the latest works for the most people with the least effort.

**Comment by morvael** [comment]
I wanted to see correct collector numbers for assembling decks from a collection of original FFG cards so new prints doesn't help me.

But I think I found a workaround for this using import (you only have to blindly pick correct card from the list of the same titles).
