### ISSUE TITLE
Profile Updates failing with internal server 500 error

### ISSUE THREAD

**Issue by rholden** [Null-Signal-Games/netrunnerdb#77]
Trying to make any modification to the user profile is failing with:

> 503 Service Unavailable
> Oops! An Error Occurred
> 
> The server returned a "500 Internal Server Error".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by alsciende** [comment]
Hi,

Thank you for the report. I fixed it.

Alsciende

Le 29 décembre 2016 à 23:04, Richard Holden <notifications@github.com> a écrit :

Trying to make any modification to the user profile is failing with:
503 Service Unavailable
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
