### ISSUE TITLE
Archived Memories doesn't appear in deckbuilder

### ISSUE THREAD

**Issue by rubert** [Null-Signal-Games/netrunnerdb#775]
I'm trying to build a deck and add Archived Memories to it on 10/202023. I've got FFG Core Set as the only available cards and Archived Memories doesn't show up.

![image](https://github.com/NetrunnerDB/netrunnerdb/assets/744702/f44e131d-c65f-4bd3-a4fc-727e6d1cd593)

Here's the Collection options:
![image](https://github.com/NetrunnerDB/netrunnerdb/assets/744702/149cc092-8efb-4b72-a33b-659c68048ff5)

**Comment by plural** [comment]
If you are using the current banlist (look under the list of cards in your deck on the left), Archived Memories is banned.

https://netrunnerdb.com/en/banlists

**Comment by rubert** [comment]
Woops. I needed to disable the banlist. Thanks!
