### ISSUE TITLE
Not letting me delete decks

### ISSUE THREAD

**Issue by RotomAppliance** [Null-Signal-Games/netrunnerdb#78]
Apologies if mentioned already elsewhere. 

I can't seem to delete any decks. Whenever I hit the delete button, it simply get taken back to the top of my  list of decks, but with no deletion happening. 

I tried most basic things, like logging out and back into my account, refreshing the screen, etc. Do you know what might be causing this?

**Comment by alsciende** [comment]
I have no idea what could cause this, except a faulty session. Do you still have the problem?
