### ISSUE TITLE
Activity notification produces multiple copies of its icon in the toolbar

### ISSUE THREAD

**Issue by finnbar** [Null-Signal-Games/netrunnerdb#796]
![Multiple notification icons from the User tab](https://github.com/NetrunnerDB/netrunnerdb/assets/4217801/5612d8c7-8de9-473c-b341-8ff8608ffc01)

On publishing a deck, I got an Activity notification (expected although a little odd, since by default a user follows themself), which then propagated to give three icons instead of one in the toolbar.

I would try and test this more, but I have no easy way to send myself an Activity notification. There's a large tournament today which may get me a few more Activity notifications in the coming days, so I will keep an eye out.

This screenshot was taken on Firefox 120.0.1.

**Comment by AlexRodwell** [comment]
Appears to have been a non-specific query selector targeting too many `<span>` elements in the account section in the navigation, have updated it to address this.
