### ISSUE TITLE
Triple notification badge?

### ISSUE THREAD

**Issue by francescopellegrini** [Null-Signal-Games/netrunnerdb#797]
<img width="268" alt="image" src="https://github.com/NetrunnerDB/netrunnerdb/assets/1105053/91b61b6f-ceeb-4849-b501-95c28ed9e4d1">

Apparently not related to the dark mode, I tried switching it on and off to see if the bug would fix but with no succcess.

**Comment by AlexRodwell** [comment]
Also reported in this issue https://github.com/NetrunnerDB/netrunnerdb/issues/796, which I've made a pull request to resolve said issue issue, so marking this as a duplicate, and I'll close once the other has been merged.
