### ISSUE TITLE
Card image on hover displays in triplicate, covers text

### ISSUE THREAD

**Issue by ericstubley** [Null-Signal-Games/netrunnerdb#800]
I'm seeing the card images in the hover tooltips displayed strangely. The card images display in triplicate (looks like with several different croppings) and the positioning is such that for ICE they often cover some of the text. I think this started with the Dec. 31 update. Interestingly I only see this in chrome (version 120.0.6099.199) and not in safari. 

<img width="1159" alt="Screenshot 2024-01-06 at 10 11 36 PM" src="https://github.com/NetrunnerDB/netrunnerdb/assets/1367539/6466385f-0dae-468e-b429-9c5bc63ff243">
<img width="887" alt="Screenshot 2024-01-06 at 10 12 05 PM" src="https://github.com/NetrunnerDB/netrunnerdb/assets/1367539/e318425b-fd33-4442-a396-ba42ecb31281">

**Comment by AlexRodwell** [comment]
Possibly caching, as I had the same issue until I force cleared/reset my cache for NRDB, if you could give that a try, otherwise I'll take another look, as it appears in screenshot that it's still using the old CSS/SVG mask.

**Comment by ericstubley** [comment]
That did the trick, good catch! Closing the issue
