### ISSUE TITLE
Dark mode colours

### ISSUE THREAD

**Issue by AlexRodwell** [Null-Signal-Games/netrunnerdb#803]
Small issue with using a pure white `#FFFFFF` hex value for general text on NRDB in dark mode, should be decreased slightly so it's easier on the eyes at night, see discussion from GLC for screenshots: https://discord.com/channels/425105101451952128/822475344669835315/1195483726398894143

**Comment by distributive** [comment]
I'm pretty sure this got fixed

**Comment by AlexRodwell** [comment]
Yep, the `<body>` color is set to `#c8c2bc` via `--nrdb-color--text` CSS variable.

Closing.
