### ISSUE TITLE
Click to show deckbuilding restrictions as a list

### ISSUE THREAD

**Issue by doorisajar** [Null-Signal-Games/netrunnerdb#81]
When looking at a deck, I can see a list of deckbuilding restrictions (MWL 1.1, ANRPC 1.0, etc). These appear as links, but clicking on them does nothing. It would be awesome if clicking the link took us to a page showing what those deckbuilding restrictions are (e.g. which cards were on that version of MWL, whether Astro was limit 1 per deck or 3, etc).

**Comment by plural** [comment]
this was resolved by the recent https://netrunnerdb.com/en/banlists page.
