### ISSUE TITLE
Can't export "Pretty" Mary da Silva in Jinteki.net format

### ISSUE THREAD

**Issue by pat-gardner** [Null-Signal-Games/netrunnerdb#815]
The Jinteki.net format deck export doesn't work with "Pretty" Mary da Silva. It looks like it's using quotation mark characters that Jnet doesn't recognize.

Compare to Hannah "Wheels" Pilintra, which uses regular quotes (ASCII 0x22), "Pretty" uses Unicode left and right double quotes (U+201C and U+201D). 

To reproduce:
1. Create a deck that contains "Pretty" Mary da Silva and save it.
2. Choose the "Jinteki.net format" export option and copy the deck.
3. Create a new deck on Jinteki and paste the results
4. "Pretty" isn't recognized
![image](https://github.com/NetrunnerDB/netrunnerdb/assets/39884514/964a5592-7081-4bba-8883-c7d525822a6b)

**Comment by plural** [comment]
we are pushing a fix for this on the NRDB side tonight.  Clear your cache in a bit and it should be sorted.
