### ISSUE TITLE
Longer login sessions

### ISSUE THREAD

**Issue by curious-attempt-bunny** [Null-Signal-Games/netrunnerdb#82]
The timeout after login is currently pretty short (a day or less?) I propose making the session last for 30 days. I occasionally run into the problem of getting logged out with unsaved data. Lengthening the duration of the session would minimize this.

**Comment by curious-attempt-bunny** [comment]
I'm not familiar with Symfony, FOSUserBundle, or PHP. Still, it looks like these settings are the relevant ones:

https://github.com/Alsciende/netrunnerdb/blob/990d3f834d77281868a607d974dc5cf05eadecc7/app/config/config.yml#L114

(1 hour, 44 minutes) and possibly

https://github.com/Alsciende/netrunnerdb/blob/45263b339a46dca9b476ece1ac006d1df1e942dd/app/config/config.yml#L24

(50 minutes? `3000000/(60 x 1000)`)

**Comment by curious-attempt-bunny** [comment]
FOSOAuthServerBundle looks to be the most promising avenue (hopefully the auth setting is independent of the session cookie lifetime setting):

https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/1b851d77f3535396d20a402f57a3781bc6548409/Resources/doc/configuration_reference.md#L40

**Comment by curious-attempt-bunny** [comment]
I propose updating [this setting](https://github.com/Alsciende/netrunnerdb/blob/990d3f834d77281868a607d974dc5cf05eadecc7/app/config/config.yml#L114) from `5184000 ` to `43200000` (30 x 24 x 60 x 1000 -- i.e. 30 days).

Let me know what you think. If you prefer I can try and validate that this setting has the intended effect by running it locally (I'd rather not because I imagine I'd need to register localhost with the oauth server - unless you have good hacks for testing locally that you can share with me).

The site is awesome and I would love to see a change like this. Thanks for taking the time to consider this issue!

**Comment by curious-attempt-bunny** [comment]
I think I'm wrong here, and in fact the FOSOAuthServerBundle is not being used for browser-based login (it's for the API, doh). I don't see any OAuth flow to the login process.

Instead what I'm seeing after login in the browser is the session cookie being established. So this looks to be where the auth is recorded:

![image](https://cloud.githubusercontent.com/assets/51608/21998539/460c324a-dbea-11e6-8dfe-7833a19d4ae9.png)

Note here that my login was at 8:50pm GMT, and the screenshot shows expiry at 2pm in four days time.

**Comment by plural** [comment]
I think we fixed this a while back.

Sessions last > a month now.

This is from a login from Feb 7th, showing an expiration of March 10th.

![Screenshot 2022-02-07 11 30 18 PM](https://user-images.githubusercontent.com/396562/152924285-fc5c18b7-4598-4c03-bc99-7846c10b8460.png)
