### ISSUE TITLE
Normalise card search in deck editor

### ISSUE THREAD

**Issue by Smashman** [Null-Signal-Games/netrunnerdb#83]
Normal card search has name normalisation. So you can search for "sifr" or "deja" and the search comes up with the cards that have accents.

https://netrunnerdb.com/find/?q=sifr

I would like to recommend this for the deck editor too.

**Comment by plural** [comment]
one other issue related to this is that all-caps searches don't work.  

Compare 
https://netrunnerdb.com/find/?q=skorpios (works)
https://netrunnerdb.com/find/?q=Skorpios (works)
with
https://netrunnerdb.com/find/?q=SKORPIOS (does not work)

**Comment by alsciende** [comment]
That means adding a title_canonical field to each card. That field would be updated on any doctrine persist/update event, using the cocur/slugify library.
