### ISSUE TITLE
Spin Doctor's flavour text has Funhouse's flavour text appended to it

### ISSUE THREAD

**Issue by webbedspace** [Null-Signal-Games/netrunnerdb#830]
![image](https://github.com/user-attachments/assets/fd2da82f-c2e2-4325-9461-7cb1d7e34e41)
See image

**Comment by talha-ahsan** [comment]
Huh we already fixed that earlier in the JSON. I wonder if we need to do a quick redeploy

**Comment by plural** [comment]
fixed.
