### ISSUE TITLE
ability to use "&" operator in card search syntax

### ISSUE THREAD

**Issue by jaimefps** [Null-Signal-Games/netrunnerdb#837]
Long time fan of the game and the app. 
Thanks for the amazing work ya'll have done. 

Feature request:
Any chance you can add an "&" operator to the card text search?
Currently it supports "|" operator for OR, but it'd be amazing if I could also search with "AND". 

For example: `x:remove&tag` for all cards that might have effects tied to removing tags, but have slightly different wording.

Thanks.

**Comment by NoahTheDuke** [comment]
This is accomplished by just using `x` multiple times: `x:remove x:tag` will return all cards with text containing both "remove" and "text", as seen [here](https://netrunnerdb.com/find/?q=x%3Aremove+x%3Atag&sort=name&view=text&_locale=en).

**Comment by jaimefps** [comment]
@NoahTheDuke thanks for the response! I'll close the issue then.
