### ISSUE TITLE
The Play Formats page is outdated

### ISSUE THREAD

**Issue by Jinksey** [Null-Signal-Games/netrunnerdb#840]
The [Play Formats](https://netrunnerdb.com/en/formats) page is outdated. 

The Startup list does not include Rebellion without Rehearsal as a valid card set

The Standard list links to an outdated ban list.

**Comment by plural** [comment]
Startup is ok - it has Liberation the cycle - we only show sets when only some of a cycle is out there.

Standard is getting updated today, thanks for the nudge!

**Comment by plural** [comment]
fixed.  Will be updated again friday for the new ban list taking effect.
