### ISSUE TITLE
Feature Request: Allow 3 copies of AstroScript Pilot Program in casual decks

### ISSUE THREAD

**Issue by TblaLinus** [Null-Signal-Games/netrunnerdb#85]
Making AstroScript limited to 1 per deck makes it impossible to create a legal NBN deck from the core set.
For people like me who play quite a lot with only the core set it would be nice to be able to choose whether AstroScript is limited or not.

**Comment by ghost** [comment]
the core set has two of the AstroScript, when making a legal deck from the core set only, you should be allowed at least two like the core set actually has.

**Comment by alsciende** [comment]
I understand, but I'm not the one who makes the rules. The card has been errated by FFG to be "Limit 1 per deck", so it is. The deckbuilder abides by the official rules.

**Comment by ghost** [comment]
Try again, nowhere on it does the card in the core set say limit 1 per deck, which leads me to believe you have an old generation card under new generation rules. So double check that card. Also, if it really is limit one per deck, than why does the core set include two for the pre made deck. I find it very hard to believe that the nbn deck is the only pre made deck that is not legal.

**Comment by alsciende** [comment]
@shadow-studios I'd appreciate that you use a different tone here. If you have a doubt, ask clarification. If you disagree, provide proof. But don't boss me around.

Regarding AstroScript Pilot Program, you can find the latest official FAQ, with *official* card erratas, here: https://www.fantasyflightgames.com/en/products/android-netrunner-the-card-game/. And I'm quoting:

> Errata overrides the originally printed information on the card it applies to.
