### ISSUE TITLE
Text encoding errors in decklist notes/descriptions

### ISSUE THREAD

**Issue by jgengelhardt** [Null-Signal-Games/netrunnerdb#864]
Text encoding is broken after I edit a decklist note. For example, this one was fine until I edited it recently. I tested another decklist note, and the text was fine there until I edited it.

![Screenshot 2024-11-01 140645](https://github.com/user-attachments/assets/d3ee039f-d3d0-4cae-890d-069395f634c5)

**Comment by Lif3line** [comment]
Also seeing this, but I can see people posting recent decklists with Markdown formatting working fine. Is there a workaround?

**Comment by plural** [comment]
If you type notes when publishing a decklist they will be ok. It’s only the display of saved notes for a deck that are jacked right now

**Comment by xdg** [comment]
I believe this was introduced in PR #846, which was in response to #776. That PR re-escapes on every save, which corrupts notes in a pretty frustrating way for users.

Looking at the code, it looks like some HTML sanitization was already being applied as part of markdown transformation:

From `src/AppBundle/Service/TextProcessor.php`:
```
    /**
     * Returns the processed version of a markdown text
     */
    public function markdown(string $string)
    {
        return $this->img_responsive($this->purify($this->transform($string)));
    }

    /**
     * removes any dangerous code from a HTML string
     *
     * @param string $string
     * @return string
     */
    public function purify(string $string)
    {
        return $this->purifier->purify($string);
    }
```

I suggest reverting #846 and exploring using the HTML Sanitizer instead of HTML escaping.

**Comment by Phelpysan** [comment]
Also experiencing this. Apostrophes, quotation marks and line breaks are all affected, and if one saves the deck repeatedly, the symbols stack up.

**Comment by xdg** [comment]
My research so far, based on a local docker version of netrunnerdb, after reverting:
* Previews in the deck editing notes section are not sanitized -- these are direct JS renderings of the text box
* Previews in the "publish deck" dialog are not sanitized -- similarly I think these are JS
* Viewing a private deck is not sanitized (for both owner and anonymous guest viewer)
* Published decklist descriptions ARE sanitized
* The edit dialog for published decklist descriptions are not sanitized

The data model, IIUC:
* `description` → this is what  is rendered in preview and view of private decks
* `rawdescription` → rendered from markdown/HTML on publish; this is what is rendered for published decks and is where sanitization is applied after markdown→HTML transformation.

So, at least for deck descriptions, there should be no XSS for published decks, but there is for private decks shared around.  I have not investigated reviews and deck comments.

~I have a commit that fixes the deck editing preview and will keep chipping away at the rest as I have time.~ I have commits that fix all the private deck issues and editing published decklists.  I'll look at comments/reviews when I have a chance.

**Comment by xdg** [comment]
@plural @NoahTheDuke -- ~thoughts on reverting #846 now to unbreak this for users, even without a full XSS fix?~

I have submitted #868 which both reverts and addresses the XSS issue.
