### ISSUE TITLE
api/2.0/private/deck/publish returns HTTP 503 error

### ISSUE THREAD

**Issue by gereons** [Null-Signal-Games/netrunnerdb#9]
As the last step to porting Net Deck over to the new API, I'm trying to publish decks.

I'm calling the endpoint like using
`curl --data @pub.json -H"Content-Type: application/json" https://netrunnerdb.com/api/2.0/private/deck/publish?access_token=$TOKEN`

and pub.json contains 

```
{
    "deck_id": 691274,
    "name": "Publish Test"
}
```

691274 is one of my valid decks: https://netrunnerdb.com/en/deck/view/691274
Result is a HTTP 503 response instead of a JSON object

**Comment by alsciende** [comment]
Thank you for your patience in testing API 2.0 :)

**Comment by gereons** [comment]
You're welcome :)

Unfortunately, I still can't get this request to work. I did manage to get the "identical deck has already been published" error message once, all my other tests are now returning HTTP 500 responses.

Equally unfortunately, I can't get NRDB up and running locally, I'll open a new issue with the details for that problem.

**Comment by alsciende** [comment]
I forgot to deploy...

**Comment by alsciende** [comment]
Ok, it's deployed.

**Comment by gereons** [comment]
Thanks, looks good now. I'll run some more tests soon and if all goes well, both updates for Net Deck and NRTM will be rolled out well before the retirement date of the old API.
