### ISSUE TITLE
Searching for in-text Symbols

### ISSUE THREAD

**Issue by Cyber-Shark** [Null-Signal-Games/netrunnerdb#90]
In order to search for a symbol (example click symbol) I need to type this:

x:click]

when I should type

x:[click]

It only works for me if I leave off the first bracket, is this how it is supposed to work, am I doing something wrong? It is this way of all the symbols; credit, MU, etc...

**Comment by NoahTheDuke** [comment]
You can wrap the whole thing in quotes and it works: `x:"[click]"`
