### ISSUE TITLE
Cannot add Quarantine System card to deck

### ISSUE THREAD

**Issue by Saintis** [Null-Signal-Games/netrunnerdb#92]
As mentioned in the card data repo issue (https://github.com/zaroth/netrunner-cards-json/issues/170) Quarantine System does not show up in the deckbuilder and it is not possible to add it to a deck. 

Tested on a Weyland deck.
Uploading a deck containing Quarantine System from NetDeck iOS app does not work either (all copies of Quarantine System are missing).

**Comment by alsciende** [comment]
I can add Quarantine System just fine to my deck in the deckbuilder. Did you check Daedelus Complex in the Collection tab?

**Comment by alsciende** [comment]
I recently updated the site data. Can you test again with an upload from NetDeck?

**Comment by Saintis** [comment]
Seems the issues is with either iOS safari, or just my iPhone brower's cache. Decks now display and upload properly on OS X Safari.
