### ISSUE TITLE
Show MWL status on card page

### ISSUE THREAD

**Issue by alsciende** [Null-Signal-Games/netrunnerdb#94]
It would be really cool if there was a small info box showing this is on the latest MWL. With the star used for the inf penalty in the deckbuilder, and maybe a tiny one sentence explanation of the meaning.

**Comment by NoahTheDuke** [comment]
Will now need to be modular, to show MWL 1.0 and 1.1 with the stars, versus MWL 1.2 with universal influence (maybe also stars?).

**Comment by AdrianHerber** [comment]
I think it'd probably be sufficient to only show the current MWL status? Old MWL status is far less important.

**Comment by NoahTheDuke** [comment]
True, but for both historical and informational reasons, it's nice to have all information on "one" page. I know netrunnerdb is not Gatherer, but I consider Gatherer to be the gold standard of included information: [Firebolt](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426609), [legality](http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=426609)

**Comment by alsciende** [comment]
Sure. The data is there anyway, we just have to display it in a user-friendly fashion.

**Comment by NoahTheDuke** [comment]
Done.
