### ISSUE TITLE
Add support of King of Subways alternate MWL?

### ISSUE THREAD

**Issue by presheaf** [Null-Signal-Games/netrunnerdb#96]
The community banlist/MWL change used by King of Subways [here](https://forum.stimhack.com/t/kos-rule-set-even-after-kos/8747) was received positively enough that there is a bit of interest in keeping it around. Could support for it be added to the deck builder? 

The changes are as follows:

Ban List:
24/7 News Cycle
Aaron Marrón
Blackmail
DDoS
Faust
Rumor Mill
Sensie Actors Union
Şifr
Friends in High Places

ON the MWL:
Temujin Contract
Accelerated Diagnostics

OFF the MWL:
Prepaid VoicePad
Desperado

**Comment by yads** [comment]
This can probably be closed
