### ISSUE TITLE
Inconsistent likes/favorites after renaming deck

### ISSUE THREAD

**Issue by Sheshonk** [Null-Signal-Games/netrunnerdb#98]
When I published a deck, I had a horribly long name that I didn't realize was truncated.  Instead of leaving it in a weird state, I edited the deck name to be shorter.  Now when I look at the previous URL and the new one, my deck has a different number of favorites / likes.

https://netrunnerdb.com/en/decklist/42010/nash-equilbrium-how-i-learned-to-stop-worrying-about-rumor-#
https://netrunnerdb.com/en/decklist/42010/nash

Screenshots of current state:
http://imgur.com/a/JFI1F

**Comment by alsciende** [comment]
This is a cache issue. The url with the previous deck name was hitting the cache and returned the old likes count. The url with the new deck name wasn't hitting the cache and returned the new likes count.
