### ISSUE TITLE
Switching language in search result page fails

### ISSUE THREAD

**Issue by pjhades** [Null-Signal-Games/netrunnerdb#99]
The search result page has a URL like `https://netrunnerdb.com/find/?q=medium`, if we switch the language, it becomes `https://netrunnerdb.com/find/?_locale=zh` which would not show any card information.

I think if the search result contains only one card, the card page should be displayed instead of the search page, then switching the language would not be a problem.

This may be easy to fix I guess.

**Comment by plural** [comment]
closing out issues we couldn't reproduce.
